---
ansible_user: barrelmaker
cluster_user: barrelmaker
email_address: nolancooper97@gmail.com
cert_expiration_seconds: 604800  # 7 days
cluster_domain: "{{ cluster_host }}.{{ local_domain }}"
cluster_host: poseidon
cluster_port: 16443
cluster_vip: 192.168.15.60
local_domain: lan
local_storage_dir: /home/barrelmaker/backup
local_storage_node: hermes
microk8s_channel: 1.31/stable
upstream_dns: 192.168.15.1
metallb_ip_range: 192.168.15.60-192.168.15.69
cert_manager_version: "1.16.1"
ingress_nginx_version: "4.11.3"
metrics_server_version: "3.12.2"
metallb_version: "0.14.8"
kube_prometheus_stack_version: "65.4.0"
