---
ansible_user: barrelmaker
cert_expiration_seconds: 2592000  # 30 days
cluster_host: poseidon
cluster_port: 6443
cluster_user: barrelmaker
cluster_vip: 192.168.15.40
external_domain: barrelmaker.dev
install_disk: /dev/nvme0n1
interface_name: enp86s0
local_domain: lan
nas_host: soteria
node_names:
  - node1-poseidon
  - node2-poseidon
  - node3-poseidon
ntp_server: 192.168.15.1
talos_config_dir: /home/barrelmaker/.talos
talos_version: "1.10.2"
workload_namespace: barrelmaker

# NUT connection
nut_host: ups@192.168.15.30
nut_user: remoteuser
nut_password: hunter2

# Service versions
cert_manager_version: "1.17.2"
ingress_nginx_version: "4.11.5"
metrics_server_version: "3.12.2"
metallb_version: "0.14.9"
prometheus_crds_version: "20.0.0"
kube_prometheus_stack_version: "72.7.0"
longhorn_version: "1.9.0"

# Service configuration
email_address: nolancooper97@gmail.com
metallb_ip_range: 192.168.15.60-192.168.15.69

# Templated variables
cluster_domain: "{{ cluster_host }}.{{ local_domain }}"
nas_domain: "{{ nas_host }}.{{ local_domain }}"
