---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord
stringData:
spec:
  route:
    groupBy:
      - alertname
      - job
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    matchers:
      - name: alertname
        value: Watchdog
        matchType: '!='
    receiver: discord
  receivers:
    - name: discord
      discordConfigs:
        - apiURL:
            name: discord-webhoook-url
            key: url
