apiVersion: v1
kind: Secret
metadata:
    name: internal-ui-basic-auth
stringData:
    .htpasswd: ENC[AES256_GCM,data:z66RMgYebh+2wnqjS/b13X7TMl75IwNPFN5MzHkjOKAaKgIcEzEjZSYjLi+aEuUevNr1iXoBJ4o6Q3GN6jSm8omK,iv:YetlN/qaB8cQnx4tbuH8QAUfWV31H2+M1o6d1DkCuFo=,tag:lUzddg7GdsH6SQeo7B9eNQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbzlNeEpkN0gwSlo4WjJ4
            SmJGU21rRWJLNCtPQzVxVXVQTWM2ZzZraFhjCnRVVDB0djdxNGhQNEJRTEVTK3Bl
            UFBRV2tiQ1FidHY5Qy9uOWFJUHpWNDgKLS0tIGhUbGVyWVZsZHFJVlI4SVFLT3JW
            NXozeC9iWEU5ejF2OFB2dXNIZ3FrUHcKYjqAerQKyMSJ8SkZ9SIkfaYl9Quq1Tv7
            HuL22POINmbqW2jf1kINGAnoRhmSlKgDl88FYM7b3e1jJq90Sb936g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^credentialsJson|.*[Pp]assword$)
    lastmodified: "2026-06-11T01:29:59Z"
    mac: ENC[AES256_GCM,data:HG4QCKGwIVu2GCi4RfI2MkFBlIki8n2yzJp5hmaglqOOfc3A0RfpEPfsyPwAJReBTUFRAB/56ARLRiQUvT+2x9xMvDRprGTTw+u7s7lgvvxddMkIFuotVgdvuJlcP/wIdrwjoqUexumAWbHCf5lrn16tdMbBdzKV0sqFd6g3JrI=,iv:Jt4PdVpVi8DPpX/upsq/5T1m5fZv1sCgTml0cNr2E+g=,tag:GTZ2MgK5qcquPJRtZK/mXg==,type:str]
    version: 3.13.1
