apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
stringData:
    api-token: ENC[AES256_GCM,data:VXm0XVfzI7QdcuSQtPLebyEThRZNg18/S5DLdMRxdmBS+NFPp1o05rUfJVkbTMa9wZJS++g=,iv:eOxHoDlesOMqS8cPMuwrAMpG8FLFLEPP70zAOfgNlv4=,tag:5eqtqJnupwksdhnL4KYX6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1enVGb1k3TUtHYS9RNXZP
            MjZRUHhBbW9xUWZaK25GM1FLcndTd2RUY2lzCkt2QzRlNStqQytaVTJYRGl6QUxJ
            KzJpbG1KeEdQZjcxRDRzQWo1RFgwR2cKLS0tIHUxd0M1bmMrci84Z0MvYmZWMzZW
            MzlzT0V0d1B0NU9EaytFODBLcmpaaHMKgBvYKXCMIGuFsQuksUr+NJaOagjMr+Nw
            WEVoSI9paobepUTsiLiL+05VMCSRcYBZcoESd5Qdx2BReN8v9qL2yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^credentialsJson|.*[Pp]assword$)
    lastmodified: "2026-06-25T00:54:17Z"
    mac: ENC[AES256_GCM,data:IllYhgg24PpLWNufaKFQx3Hk4X3cFAiXs/oyYmPiaIBr5k7/Twx6Gt5XDbS64b/F71bWer7SYxhXjnjFhToKmZ9P6xRrrUhlueiPssy08mV2Y36joMuK3fqqLzW6BE/bsdoM2YVNTk9EOYfasYqj1OYZ8M+tBQ6WeAhDv6vgqew=,iv:DOAC/i/SFmd2YMGKyQzfZA1Jm6ntRrIDJBW7vhF655c=,tag:b1Una27VZIweZTPzh4Hzgw==,type:str]
    version: 3.13.1
