apiVersion: v1
kind: Secret
metadata:
    name: internal-ui-basic-auth
stringData:
    .htpasswd: ENC[AES256_GCM,data:GaLI9SAbJ3MHArXo1ZN7Dz4yFmlNvroe1q3PUpbTQ7evpYx4SdBW,iv:OhoHH7/1wqGaHYeEHJLtkLic8smAXBHX2k6qtXrGYGU=,tag:ERmJZXzzLMb6QVsFKJca6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Q2VmdHJodzE3OUNmWTAr
            RUg1RkxNeWlMSUkzdlE0LzVwdjlMbnRmVlY4CnVWSzJEd3JmRW9ML0ducHZqNnc2
            cjdESHh3MEtoWlU3OFRDWEsybjROK3cKLS0tIDVMdFdNeklNTzFKQU5PUml3Nktk
            UGhGZy9oL1VKRFI4NUJUUGhKamFkd2cK+tbfwutS7W5nEFZzRj3zg+q9mTrgG1Me
            DXd8o423V+DlBFlnn/LvQ9T479otYI7pwyYamUvkV7bSW6BFPTef6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^credentialsJson|.*[Pp]assword$)
    lastmodified: "2026-06-11T03:39:55Z"
    mac: ENC[AES256_GCM,data:dBm4wtazQ7QIxxljE5pS4IK7qPasHsgaOhuso/gQYB+gyZEgRspF+qf5M96b6Q5q2HIVLhB6idWdg87Vq1HbEaBGi5GvzzR9Baywo8bGU2zQdoHZtUdq/R+NROU0zGZeya3zlJvzpG2YHbashOdB+g63j6F65XCg0oN5s1Pa8UY=,iv:aS8Q/RdETb+kHWd1y5pS5ZotgL0JptNG9tCDIc9L6KA=,tag:qDWV+kLVSQuaNjK3I6hx/Q==,type:str]
    version: 3.13.1
