---
galaxy_info:
  author: Nolan Cooper
  description: Install and configure the dewpoint Govee sensor Prometheus exporter.
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions: [all]
    - name: Ubuntu
      versions: [all]
  galaxy_tags: [monitoring, prometheus]

dependencies: []
