---
creation_rules:
  - path_regex: .*\.sops\.ya?ml
    encrypted_regex: '(^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^rootPassword|^password)'
    key_groups:
      - age:
        - age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
