---
- hosts: hermes
  vars:
    key_file: "{{ ansible_env.HOME }}/.kube/{{ cluster_user }}.key"
    csr_file: "{{ ansible_env.HOME }}/.kube/{{ cluster_user }}.csr"
    crt_file: "{{ ansible_env.HOME }}/.kube/{{ cluster_user }}.crt"
    cluster_crt_file: "{{ ansible_env.HOME }}/.kube/cluster.crt"
  tasks:
    - name: Create kubeconfig directory
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: "0755"

    - name: Set owner of kubeconfig directory to {{ ansible_user }}
      become: true
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        recurse: true

    - name: Generate User Private Key
      delegate_to: localhost
      community.crypto.openssl_privatekey:
        path: "{{ key_file }}"

    - name: Generate User CSR
      delegate_to: localhost
      community.crypto.openssl_csr:
        path: "{{ csr_file }}"
        privatekey_path: "{{ key_file }}"
        common_name: "{{ cluster_user }}"

    - name: Delete Any Existing User CSR Objects
      kubernetes.core.k8s:
        state: absent
        api_version: certificates.k8s.io/v1
        kind: CertificateSigningRequest
        name: "{{ cluster_user }}"

    - name: Create User CSR Object
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', './definitions/csr-user.yaml') | from_yaml }}"
      vars:
        user_csr_base64: "{{ lookup('file', '{{ csr_file }}') | b64encode }}"

    - name: Approve User CSR
      ansible.builtin.command: kubectl certificate approve {{ cluster_user }}

    - name: Get User Certificate
      kubernetes.core.k8s_info:
        api_version: certificates.k8s.io/v1
        kind: CertificateSigningRequest
        name: "{{ cluster_user }}"
      register: user_cert

    - name: Save User Certificate
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ user_cert.resources[0].status.certificate | b64decode }}"
        dest: "{{ crt_file }}"

    - name: Get Cluster Certificate
      kubernetes.core.k8s_info:
        api_version: v1
        kind: ConfigMap
        name: kube-root-ca.crt
        namespace: kube-system
      register: cluster_cert

    - name: Save Cluster Certificate
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ cluster_cert.resources[0]['data']['ca.crt'] }}"
        dest: "{{ cluster_crt_file }}"

    - name: Create User Namespace
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', './definitions/namespace-user.yaml') | from_yaml }}"

    - name: Create User Role Binding
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', './definitions/rolebinding-user.yaml') | from_yaml }}"

    - name: Create User Resource Quota
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', './definitions/resourcequota-user.yaml') | from_yaml }}"

    - name: Create User Limit Range
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', './definitions/limitrange-user.yaml') | from_yaml }}"

    - name: Create User in Kubeconfig
      delegate_to: localhost
      ansible.builtin.command: >-
        kubectl config set-credentials {{ cluster_user }}
        --client-key={{ key_file }}
        --client-certificate={{ crt_file }}

    - name: Create Cluster in Kubeconfig
      delegate_to: localhost
      ansible.builtin.command: >-
        kubectl config set-cluster microk8s-cluster
        --server=https://{{ ansible_host }}:{{ cluster_port }}
        --certificate-authority={{ cluster_crt_file }}

    - name: Create Context in Kubeconfig
      delegate_to: localhost
      ansible.builtin.command: >-
        kubectl config set-context {{ cluster_user }}
        --cluster=microk8s-cluster
        --user={{ cluster_user }}
        --namespace={{ cluster_user }}

    - name: Use Context in Kubeconfig
      delegate_to: localhost
      ansible.builtin.command: >-
        kubectl config use-context {{ cluster_user }}
