---
- name: Set Talos
  import_playbook: talos_setup.yaml
- name: Setup Cluster User
  import_playbook: cluster_user.yaml
- name: Setup Core Services
  import_playbook: core.yaml
- name: Deploy Workloads
  import_playbook: workloads.yaml
