---
- name: Install Cluster
  import_playbook: cluster_install.yaml
- name: Setup Cluster User
  import_playbook: cluster_user.yaml
- name: Setup Cluster Services
  import_playbook: cluster_services.yaml
- name: Deploy Workloads
  import_playbook: cluster_workloads.yaml
