---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  dataLocality: strict-local
  numberOfReplicas: "1"
