---
user_kube_dir: "{{ ansible_facts['env']['HOME'] }}/.kube"
user_key: "{{ user_kube_dir }}/{{ user_name }}.key"
user_csr: "{{ user_kube_dir }}/{{ user_name }}.csr"
user_crt: "{{ user_kube_dir }}/{{ user_name }}.crt"
user_api_crt: "{{ user_kube_dir }}/cluster.crt"
user_kubectl_cnpg_architectures:
  aarch64: arm64
  x86_64: x86_64
user_kubectl_cnpg_checksums:
  arm64: sha256:1e9d0e1f7bcd24b1d9a505f9a70c100fbe10ec0386dad0ad6aafcc0299049f49
  x86_64: sha256:96e69dbc8ab3786662938912da4551ed030ce9c32b09dd864c34bc90f53953d2
user_kubectl_cnpg_architecture: >-
  {{ user_kubectl_cnpg_architectures[ansible_facts['architecture']] }}
user_kubectl_cnpg_package: >-
  kubectl-cnpg_{{ kubectl_cnpg_version }}_linux_{{ user_kubectl_cnpg_architecture }}.deb
user_kubectl_cnpg_package_path: "/var/cache/apt/archives/{{ user_kubectl_cnpg_package }}"
