replicaCount: 3
obscura:
    auth:
        jwtSecret: ENC[AES256_GCM,data:KkhRk4IcRj4ib6b3MeGjffk=,iv:z747Hv4iplYFRgUuPAUB+EHLF57a0pvDj0Pf3PkS5Sc=,tag:8B9N6kxKD2pJSqOYdEOjog==,type:str]
    telemetry:
        otlpEndpoint: http://otel.monitoring.svc.cluster.local:4317
        logFormat: json
    server:
        trustedProxies: 10.244.0.0/16
    fcm:
        projectId: obscura-af88b
        credentialsJson: ENC[AES256_GCM,data:hX2VbJvFKfqquQXhtlLjXqBiBtQR+LOrU1EFTlQNz4lBA58QneRW0XysIpOy6biyqrz+9Hu3OPIYuEBbJx8JPhC2ZjepsWgv/N/7cPdhHfP1S/JPSA3DLV5A99Z9RVgCjRPyZHP0Tshl1XbMeSPI+qQYb0t4QHTZH1RTvbs0V2TTMPEinXGrFJ7BhcilK0S2Pzr8AmdK3MAkidFETBgwN14U960SrnU+X5I9/y2YHl83gcO+tARCG4mqUZsEYtTfI3z5BHuy2VBwZwZrfTRYBV4TQht7fo7J2GWUVBK9GvhxUFrXb6+SkNkI+DClojONFd/dC3naqCUQxmYSu3j8FVbEAHKPp8bLo81Av5ZK457m9KewQ9yRtl16pSxXK9WnzmqrZqT9+WzIBVQe2sLSDD5mndShBnolkplST4FLzN6dR9y5sGO2nON48PxBu9WJuJ/LbAxm1L4TqV4/l1CcbD2Y26KzG6STsSqxslFahKzm2894yFVlSWc8IUME9gsUnBJ8OkoSygqbQyOQ3/FeDGAucfmtUUsVMWsHxHVorpnTaqPF9jt+UEnjlrUleKfB6EDDO4xR5t1+UomQegfN8V8TGmVsqr/voafurLAyQNvGb1sUxHFTZj+soHMo/ab46jRtZCEmB5nKFp2+c5OzrW/xXpGozq2mPyY4ewY00eOwDAl2AFP+mTSPFXEa+m/miD5oylporHo1EBZCPC0BIFsd0YL2P9/C81mLu2bP1jwICnXI5P3lsYRBFxBk2MXKLj+Msj+Hui/kM9WWK8W1wNiHc5FkDh6haPbV54Q1AeDjM9q64ieQ4T6rltM3RXXa9brDWIUsQFynRCyb9VkWHjlJdzvMlr4Fa6x3Iv1tklF1P+fLCY+Rw5EV65vQQgsZy6fgxdZgb8LwGK7EQzYgqXe1LZ5ud6Mv5gi2MHrAFD6u2awMcYgpDfBzSRzyuHaSn3SKXAzMjcbvBLmbl/0gf3JtWi+B4aNYVsa/VmzoRM3JL/8EmPK81ldO1CQK64+r60+6aAI+C4TNuKJ7M6hhGmSzb/YuidTNYTQ8zzTV3lWiqwyq8rrgGCkkpS4F5ttlf64h9fwL+lJsSkh35BjCeY9yhsucaTdX0Gq4/bth5xDGfDrc46Dq70qkCt/HKFAtdKAebWtUnx4SoBWfYQTWxAKh6cxUZmTHB4/CnoydYdx4Qq30XTU57Tsoff9GetQHRRVXiCQnxoMxGAWaraFk3UI6lsKRl4xfxzKyZTISU1OGb3cY8I8/oKQQjhQfMKyq7FDJUWrIK41u4HZ1EJNOIIpwFiRtMSTneXV1kKh2TiM/OMGbqn2vZFsYI5wkI5LY2y3t8a24V0/QsZAce4TCgqlmOxz6MdrEzMxHWR7eUjv290bccuBgMlmZOSvqsq9ljGd3Uv9GFnkchgSEXED8mzpIxHZgckfoXYNWv4g6KfQi1XN0HRLFDZK69Z0gps+JDY6Key3SbRHsM2ddNa0nhQJQGDKrLI9aI94hf08i7/j7DjDdSggSL07ulzmpNxhfM6Yp0KQDsryyHC900613A71Gr9j2a9/+WrCGG2cfVC7QuHeGCp8Erp7MNQea6bUrrXLk4YXAP8AYBq6O0WnXlNnqvAKJzcivz9Tt/LuY49lqsNdeCk6oL3JtsXYcUYwsEK7ZlXvfU+1sYo/u2rhQkpLx93vVlOb+WuYKMfblQM82vridX/ceyR6YDvZ4djTL59JkVb6lGs8YKGLqMyJU1bIemlBWtbGoyH8eedIckKkDI0y0XRYXu8MMDdEYHboWO8Lup40Nlk4BNOpEoybLx5FwCUhZHqr/8igUACX4sDbY6zruCpSWcRLLlSbA9CYTYaM1QpITz5BmXQLvyYw6strLk2Rndn5KI7FUCvbxdEADMN1C159CjlGHSswUxv+wyc3JIHHnLNzTb/HOfTeURd/1uf31vcBfPS6DNwV0QL/SC1vwteaqGVR4nxSy4lpTscfrqahN0lnDMflNXrqaWVCdi9SG+moRvADapnAw1bhqRYL4fmun424RsZiy0wcAXr/aW745BN+DfQHTChqEanDtez8yV6lyUBg802E5glNOdirt0CXJ2e27S2bO1SVilfghPmb5YjyzFVqob9R8M+P8ka5HHD96FE+DZhMxEVqeyGqgWbmDtBhUBEabfsRR/ltUUDerpPiMp9HqLLY83GABCythKWTVRluUa2w4kb8u+5ZgfkswO/trPrEEnjvql8h+tKBLP6fMGRKMISWR3CHwLMe+KYOdYhZsNNSYGk5519Ri+NTuGkNkL2czQ+BiJCTFfaBV0pZCSe9qKmzM8BwX43y7fnU33KAo3M0z5aJJy4hbe1DVE68pOxIgco2+Gr+0VV6uDAyINMAMafmYr8CzzG11QZchep6kI+Kp8VZ4gpS3yiM3mmPQogiV43OkD98qCKzlLEdXL5pwNhFsYxKV+Ga9fahAR+ZobA0H02Jqfbvq+W0gh1DAELH/MVuAIBvUp6Bfeda17oOiCAtNViBzKhWh+qgUAY2pALjy1cm/D2Buh7b1t6RSyBlWa27uQ8M/AfKgvfT4mOnoSL36xgb7+anDt7yRBG+xMniGgoEowxYESVDnAIBZnKHX2Af/EWt8pM7sQh+uTjqJXV2ZZtGrd8O1i1ekgmWQKVKKqQQuvm87zr9e+LSpfFtR/8Mh3MoD3iAze/gm3Bf+aJy+Ns2sNIiiaqeMl/vijeTz556bzDVY4JsxcoKvTL10sEqpibKOongXdGmLdWwAGfuO45k9Ln6X93Y1fNphBs9Ut2hEaAugshcVxmq/a5NZxlqGc2qwCV0USgb0CUWbOi9VJxKIrwnAqSMPa/c+n/LZQEj+LozW7Fw/im71lcHdIOIXX+vntfGKKpdMQccAwNFPpSO5VGnH78S8EsuINQTS31aN0uNty3I3Y4vAKorMvCctwdWVW3pbkyW1x96sDZFg7/FiUy23wUfjcBKSh+LKYtp19nfrE6Cy1TytuNjdb15QitrYuRoq//vTU+Bd51McQAOJwXMof4rF5aj5FUTAMHYnufvCAJUAxegOxDPZQFt2qi+BdKBjaG1QgZoncLGdeGBngsCabEHgZuFueZwp7sLhwEOloJhVLEpt80+bg1MJKNrp5E09XBNpSuLXzI9WDjJIGHB/FepM0r8=,iv:XH/4QgBKzrTSE1t7PPNSwlZkao95Y+B1I2OjyhqA0BA=,tag:UbE4A20ip7hvTT4mJCC13Q==,type:str]
postgresql:
    enabled: true
    primary:
        resourcesPreset: none
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
            limits:
                memory: 512Mi
        persistence:
            enabled: true
            storageClass: longhorn
            size: 8Gi
    auth:
        password: ENC[AES256_GCM,data:z6v1Z1ZcVEj76fnuYJ4mcauvQg==,iv:Zn7D/IZIFKsSDhf1pn4J4zg17mvGOgHd1nsOe+d116Y=,tag:yL/sGCiGuYiSYCuKhQVfhw==,type:str]
        postgresPassword: ENC[AES256_GCM,data:0746JzFN3WNh6YTwjWBiWxeOz1jSRPMy,iv:7eh57RkkNwCTLUlxNkDO8T3TKYiHs2dlWrGmhbvBD1M=,tag:v8Pnl+GE4WvdGES+UZ293A==,type:str]
    metrics:
        enabled: true
        resourcesPreset: none
        resources:
            requests:
                cpu: 100m
                memory: 128Mi
            limits:
                memory: 256Mi
        serviceMonitor:
            enabled: true
            namespace: barrelmaker
            labels:
                release: prometheus-stack
minio:
    persistence:
        enabled: true
        storageClass: longhorn
        size: 10Gi
    resources:
        requests:
            cpu: 100m
            memory: 256Mi
        limits:
            memory: 512Mi
    rootPassword: ENC[AES256_GCM,data:gx9lR7k6HtIN6pTqDVvlDFIAOA==,iv:WfrCDK0J2wPbRVXmq+czajSj8e3tVCAhFJ6ejtE0jnA=,tag:QY2aPDaN/iAXodfNZhSGXQ==,type:str]
    metrics:
        serviceMonitor:
            enabled: true
            includeNode: true
            namespace: barrelmaker
            additionalLabels:
                release: prometheus-stack
podSecurityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsUser: 10001
    runAsNonRoot: true
    seccompProfile:
        type: RuntimeDefault
resources:
    requests:
        cpu: 100m
        memory: 128Mi
    limits:
        memory: 256Mi
securityContext:
    allowPrivilegeEscalation: false
    capabilities:
        drop:
            - ALL
httpRoute:
    enabled: true
    parentRefs:
        - name: poseidon
          namespace: envoy-gateway-system
          sectionName: https-devscura
    hostnames:
        - dev.obscura.barrelmaker.dev
    filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
                - name: Strict-Transport-Security
                  value: max-age=63072000; includeSubDomains; preload
                - name: Referrer-Policy
                  value: same-origin
                - name: X-Content-Type-Options
                  value: nosniff
securityPolicy:
    cors:
        enabled: true
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbEJ4Mld2SEhrZWdIb2Vv
            Yy9yWkRWazM5YUZNQ3c3b0o1N1JhOWtYMlg0Cmw2SnZVaTRNMUpyMFQrR3V5aHIw
            NUZwUFZGbi8vWVlrVFd5M0VHU2Y4NlkKLS0tIExWbi82RXV2Ty9TclBqQ21yV21x
            M1liTkpPMnZaYWZVcmRsT3hpRkhYTVkKTv/CPXJyV1dB9SvOQY8VimH2IsINex0x
            bhY4Ni6WqvBxO+3/BkYPmzEeUUxCwq9x46Q8HmFDf/ENvX7zhbPmhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^credentialsJson|.*[Pp]assword$)
    lastmodified: "2026-06-11T02:52:18Z"
    mac: ENC[AES256_GCM,data:d9tADRK5MEFJhKiFvj50RTWAMuGNwXPqTVNOzmAdZWFCE+cU2ncxH2bx/DgnqoOC68Q5U/8B4oS5U8X/O8EyoASFFM3f+oB+FZWFSiWYctVs/1N9J2pPEWwnYfMCYDqFExyaxXPvwb7McK9SHEea+N/LguMZXe2xOw0iBWADPVc=,iv:WUJz+HN5LpB8uagOve+/T3qjcjp9aAIuvplEHb+t8yM=,tag:TMYvKPhFv7yIDFW2CJVwTg==,type:str]
    version: 3.13.1
