replicaCount: 3
obscura:
    auth:
        jwtSecret: ENC[AES256_GCM,data:DvY4EpStokLqzh34iCe0YwE=,iv:xsZVQZEEY13e6HjwmHTCaUd66wOLOG7n4JeAlveKlBQ=,tag:oZJWRt+Ng8QzvoWrXw5XCQ==,type:str]
    telemetry:
        otlpEndpoint: http://otel.monitoring.svc.cluster.local:4317
        logFormat: json
    server:
        trustedProxies: 10.244.0.0/16
    fcm:
        projectId: obscura-af88b
        credentialsJson: ENC[AES256_GCM,data:UCH3XQmBaXhj9m7E1/ywEWepfkDkXUSp/6h6i/3E460kkg2s7uMn/ArAR/ssKBRBlbuU62N58t4p2yXit5xPfMlOYqblGQHgbQfGSWTalNgTHxBp/V1wpISAp4LMifDYRvI3uRKlQC98dZNDiCl7TeQXfW8i5GpLoyHllsG5GwMXmrWRUI71o7Odr6QQoza/Be0OqDao+e6j9d63SXzu1mwjbCy7OhK4tLKhdlJUsPFJctPzylpthiwoWMosUzZXz03pQk+3Z3fYHT9HH3zboc3P4ooBXfvUIZyAdhZfcBIGjVnWvbgx3/BlPJvD7Tg5yRICCbYJd3GDYCOuE+ugz4LumsH1jOmxdCQJYkm1kLMMqE9r9AMa+VBFw6ZAx8PQf9mlZ8r/9ePanpSglk+a2QrwacQCPAlXsQDv+Ne13qW4xfMg2aMZWyPlXicoRct3imHkpQxFy9+lKRzspIcEzzWq/IR6KPAIyIr8p6G6JTRv/Kh+eBz1sH12+1UuI7obHzBAWUqlmP3ehYc90zCb9W8VbMmL9AgMkECWX6O2z+Pd3OgCkG3kp9ptbtOmMNq3ApA0LQLZyZ3D+JyiJfanldaKRs/5Dt8kMYi8fyRt62NZ3m5byfNAzpOASvbR9BoqEIS/IUVKeIskNQ1tiE0tGDMOvwNpna75KJrVgSG25M+FrAmZXeHn5n7kbj9uOcNEI3BSJxNa6N4Viitq+EmxJYZEWKwS9gG1ShL+ISfo47Za0KtckgeTEhJ0hsWdL/gqZc+TcPtuEHj2rsXb9NTESZXpB3mkkgOttep3rX8amctJC9xPgo1lgaPBcjZOzKcLMWrw2/0d7LNLKMqnVfK2d4ul8OrVRGopnvXPl1CbGdDuLPhUpwqOGFU500qJc1aXfnLMpcFVBHCeDx8gLAJVkQh25OHNrneU8MEy3zZbpYiW7qUT5uj/nq5g9MoO/es75HWXhjWAas8jc28bAw2txXWwNuCbbaXOjhDhgdIyyW2vKRFuMcaQSfZ6VnoScCmLDB7+8bp/cwmrGF4rHmz67YLVoTCRHCxDMJfTxewympX65qYQZmqjQlJXlBf2AmecuYZPRtrA4YsPFtIVg2+XHzOw+BnntJmdWguIfxa1/hYvzH0aLFlERo0EijRsnPtfIFqdk4xAVAQ8wXiuxolFCXKl0gRsjboRis+tFq/pZVWdRBRuT7UVJwuqMmb1bHYQOhZn6m6Z0g1PFne1BgN4pSBHNjwOYjMMrLqddtel3RofrgE0Sew1AGI7PUfiRD8BA4C+Cb55yLA3tbt1pOdD2BnlHyAnbTsPXA1grg1nQX/jW2QjinSZn5apZlBUJbwFL2GE855xiQAbBqU5RJFfdBQxvGyNULvnCnJHQU4xZG3zLt9q/CfWZdUs0BjcnxNUCNIyS8WedV6qLEMTD3RQaoqC3985R1gXg2VzHFgTQOHXTkM5gy/WpU33EHdE00EA/441jOphMICiaOT5hpTmBi+sVsoeS1kTzn65mTWVMUaqFK5x9WL1WhAZ/ImX9cf2UUV1esYddxt//wsRzfMDQ9RvV6Fk+Yg9QS9W7pEO2PgjutdsYZBtw2LOya7iUcAa1lvKvwfmOg8IBUNoFjYsyY588OhvJR9jDRMxuW0yStroT8cLuwyMWxAk8S/TUif2BBASep637N8iA4VTFBPxHOX3n7Yt3XtA63CiR/6u13sMkSd9GYkbucrA9SZiT/pOuetkLoWZORw032UDCSVrwYCERMPA1e+Km1oL7I1X4tsCc8/EZg2wMB9s/QOKls2Sex455Kb1L8Du4JWGHNMZvfvQirId7+BA68XbstEl9YMEoT+UlJWJ4bSEYF7x9XLM8vKSg0RnYURJcZJzv/CxGeoMsl8ODLI/JnR0riHy++8K3CUPr0fb1yquJKEjr2PAXGrsS/FlkKRb1NfG4sK2gvp5D1aVh2HbqDlX4+X9YLrQNqzQ719KrMkWw8bJ9i09QPnsW5w9W6mA11A9r02yjNOVHXsT2tYFRjcUO3/c5zVG404QGreBIwqfT7IJg9pugtr/SqzFzNVH1uMG7/JtWEbCsgI86mbtc3Ip+333iei27wr7H4dYVsQAp32XxnNYjXWJFl2b37fHp40smjsqUuN723BxPcp7WQGY4AXKVh1XbUgfyRK/EHae7z0JCiLLwxVszgU1khz8LuvxrhzvAvWUpvdEyXUqbz96NtdrPgsvq2VymrceaH06pWreFq+aBRTkz1HUAguz4SkBmPe4VpuWDCcpZMiIf0uwS+tTT8tcTf7lxaaTHAi70x94JRRfaJnwxvxzjA/+3rqRTx08/1V4siYbjUu0QfxtA+tosUaahZ71N95Hoyka4yT4KH9IT2/6hW0ltslHEwpBL4hkqRmjSaXfxghIInIt6CHYSa3Dru/Odjwyu5R20NcC/MPelNYvaJ+TwwIxxgwfOD2i9ykFhhHfc24gRINWb8oQZz+A5N2f60JhmIVMHCNetXV7CQepP4TFS6tMpNaR2hMXgdvYzi6NnJyR7VEUuDh/03smecsaMikpY7tFCBrMYzoVSodKmsAHuVYK30lW4ZQKl9bcHjRyGuTvN4loC3oydrzDKfvPRRkzV3H5nppcsYOrzYQAPyFV8Ru+3tMoQhT+o6hUgG2SttC+HKtCJmVccWWh4J7MN/PQmX4KnUyJDzI0i1h5njJTRnqxEfp+l10MJevnJ+W/UCGz0+zGPhNwA7fg1pf/JOKcFbzNr4QWM6F0D3bEVk7NU/MPnnIwZh4J55UOKFJxFSe4nnM3Z8Gk3AvsjfTamFz+VA1hs6GrFpKg+Qb+LNZ4wSaoniUULutdbB6uqrrX+L0DMKCdsIR3wNGXTi94DSIYqxZM15Gyp4uT0Zda97srwE661fAVD18/VJJ7RcNPBQ/FNoekxKcBNC0AbCeFzOC0nkABUCejtVrGkxszn98i6IYHX0fhnPBVq+59ITwULkVIechO6aWNg2VljS5foAV8xfLPOjkci6/V/mzBF1Dk9xwdTmLnckbhlJehVX0H85y5yxXjA9nEaBlsAZO+kripe8+PDjQY5o70CkD4ZqPYdW5XZbN54Im8crOwu0MTVEaJTl2Sv2zgXumsO8IRgJAKxIrBhBHB9Hto2oWCbWG3riCRyc4+Ig5o//Bf8I3gxXHdq9o=,iv:cObhqHYYqCxwhkc/eE1rejC1JmRRvuStI0MM+0w+GQI=,tag:7bxmigVq7/Tgn7Ui3OUCkQ==,type:str]
postgresql:
    enabled: true
    primary:
        resourcesPreset: none
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
            limits:
                memory: 512Mi
        persistence:
            enabled: true
            storageClass: longhorn
            size: 8Gi
    auth:
        password: ENC[AES256_GCM,data:Q6LqP6nheAalQ0Ehx6mIQSK26w==,iv:gcEHQtCD/CT1PbFy1TMXhWXMWviJMO7zyYvk+QzgVgs=,tag:fxPvXH0qlBUWHFB7mj77Wg==,type:str]
        postgresPassword: ENC[AES256_GCM,data:++0+vo0Iase2cOEDeQHUh2y6NRej9Pdf,iv:ckgcysdXZDErx8SQwMHwl09OCG2/rr7Eed3TTPRowgE=,tag:zKhNUODUCkaPnXMuISIFpw==,type:str]
    metrics:
        enabled: true
        resourcesPreset: none
        resources:
            requests:
                cpu: 100m
                memory: 128Mi
            limits:
                memory: 256Mi
        serviceMonitor:
            enabled: true
            namespace: barrelmaker
            labels:
                release: prometheus-stack
minio:
    persistence:
        enabled: true
        storageClass: longhorn
        size: 10Gi
    resources:
        requests:
            cpu: 100m
            memory: 256Mi
        limits:
            memory: 512Mi
    rootPassword: ENC[AES256_GCM,data:brpN+CP8rykvYizvdC/F6MJLKQ==,iv:YUurSEsmIKBWZJ+ZTFCtkcTrQuBXuB3Ul9y1LhwWobA=,tag:82ZbZAYzV5GHLFPFTKbB6Q==,type:str]
    metrics:
        serviceMonitor:
            enabled: true
            includeNode: true
            namespace: barrelmaker
            additionalLabels:
                release: prometheus-stack
podSecurityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsUser: 10001
    runAsNonRoot: true
    seccompProfile:
        type: RuntimeDefault
resources:
    requests:
        cpu: 100m
        memory: 128Mi
    limits:
        memory: 256Mi
securityContext:
    allowPrivilegeEscalation: false
    capabilities:
        drop:
            - ALL
ingress:
    enabled: true
    className: nginx
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, PUT, OPTIONS, DELETE
        nginx.ingress.kubernetes.io/cors-allow-origin: https://*.obscura-client-web.pages.dev, https://obscura-client-web.pages.dev
        nginx.ingress.kubernetes.io/cors-allow-headers: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Idempotency-Key,If-Match,If-None-Match
        nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: 55m
    hosts:
        - host: dev.obscura.barrelmaker.dev
          paths:
            - path: /
              pathType: Prefix
    tls:
        - secretName: dev-obscura-tls
          hosts:
            - dev.obscura.barrelmaker.dev
sops:
    age:
        - recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN3RMdytzanhKWTIxRlg1
            Y1dmcVZlSXpveEt3eVNBd3FLdjdRQk9aL0N3CmkzUzdqWlUwK2p4cHJxbkFJYjBr
            VVkyblJNcDhYdGZyZXIrWEdrQjBEUFEKLS0tIHB5KytpS0QwWUFSVUJrOWw2cU9C
            cEY1UmkwbmFFM04vNnJBd2FxU0Q4NjQKwRJG3QIeTcQXVo2Gt7we7HX9ivYEX7SD
            XBTJwCJSLHfzAfNDsLVQg2WR39X/GQWAqdKLlYreQ+KUCVKbuaGVuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T19:28:09Z"
    mac: ENC[AES256_GCM,data:fI5U90/yGwiKp/opJMPQQWMJSA5yDt9IqdR1ZZ9SVUPlfv/CcY2EWmBdjb0e61+m8ShPHOKnZmwDWrMeGyPeRXkbB0qqZ3ER4XQpqT9OvKDPnBwa0E7BfBBX/M6dPBtuQB+aUxFEM02S2mMCvpWPX5O989OztxfPcRMVEsXhNAE=,iv:fyPQj7ZA/LWBdVT5HogUGurlthbMQ3pt40Vaen9P8H4=,tag:bu9au1mfBbgUGw5nbnS8Wg==,type:str]
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^credentialsJson|.*[Pp]assword$)
    version: 3.11.0
