server:
    password: ENC[AES256_GCM,data:PKViS7EpEyiuwg==,iv:7r8ElBxxEJgXNplylhQIySdBqOKh7qvfZDX4pbmq2CQ=,tag:s0NpKwBcXU5ZK63S+3fUTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRE5VVkR4OGdQZm5IUXlR
            YktwcjVsY0NvcFFyeDVLRy9DTFFCSW10UWtnCmFwczRoMzNFaWR0RGx2TUp4RDRz
            RlMwQmFqUTJDcUdzdGpRaUQ0K1F1bXMKLS0tIDZ6Ym51SmtsQVM1RU9iS05talYz
            SFVaYTBtR0twb0p0aERMZEsyeHlybFkKX67XAPgGf+b2HhjEGQtJzv3EY45mEMtL
            GW06dRFV8eI8EcZQUBSS8ktBVTqSrrJmvxeVvoUU5XmU90OmKl+2ug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^credentialsJson|.*[Pp]assword$)
    lastmodified: "2026-09-05T15:40:07Z"
    mac: ENC[AES256_GCM,data:K9M6dFN/MfewI9Zz0TgQQs7eXey2RZt+nus83HcJ0769NwavdkIaHRh0Cjk1yIPuC8XU5lSd9KYdbBMiYjDHLC6WEI/IZlCTcFpSmdQ06FzE5e0efCbmmFznE700XcoI/vADcIddkZ/YwaOXFNtvT0aW9xTH/Qx3g6ULM02FVLo=,iv:TFiwlSF8+5L6i7vzEHl6lVyrFdLHseNc9yCvIo6l5Zo=,tag:JohVjd7kwPNKJXeXKjBJYQ==,type:str]
    version: 3.13.3
