server:
    name: Barrelmaker's Server
    description: First 2.0 Playthrough!
    maxPlayers: 5
    public: false
    password: ENC[AES256_GCM,data:FCK86JFSw2JWWg==,iv:jOJe4Vcv/wEN1ZfCTxjxob8kgUJxu7Xz69GxWWjn6TM=,tag:6QStDak1ZAZ5nbmSPP2ffw==,type:str]
config:
    securityContext:
        allowPrivilegeEscalation: false
        capabilities:
            drop:
                - ALL
    resources:
        requests:
            cpu: 20m
            memory: 20Mi
        limits:
            cpu: 60m
            memory: 60Mi
image:
    tag: 2.0.41
persistence:
    storageClassName: longhorn
    size: 5Gi
podSecurityContext:
    runAsNonRoot: true
    runAsUser: 845
    runAsGroup: 845
    fsGroup: 845
securityContext:
    capabilities:
        drop:
            - ALL
service:
    type: LoadBalancer
    port: 34197
resources:
    requests:
        cpu: 800m
        memory: 2000Mi
    limits:
        memory: 2200Mi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbDU0VXpxTjhwWHdmSjl0
            U1FVVXVFaFVtVHJ5ZEJid3JiTE5Kd3F3Z0NjCmlLUkVCdWdTYmN6TW1mcytDVVFM
            YUtIU1hSOElVWml6VXRHdDQ5Tk94eFkKLS0tIGczejBablhHcDFGQmpDUDJNdjk2
            YjFtNy9lRzYrQ0Q1UUJNalJyZC9oMVEKOOAq/Orfy+ZHAIFNPQ2oXbBBA0nWl16H
            vVXpzw53BrMbamw6Ks5bqYVAUhAkv3ELICRTJHmNpPesDFHWnunPjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-16T18:02:20Z"
    mac: ENC[AES256_GCM,data:7Tdir0fgc/iet/dTmgmrFzIlXsdMVeIPLt8E0wxqTnDARYp7UEAJKmc7M6fcAwMWX80l0GygKy0QtBBK9dQVIkjHEFiwH72Rk1KLx/hwBiBMG+JRGdnOZj4mJxp3zY3q/+7CfY4jl93QKaj+kqCr/HFp5UCXaws/GLaNv886/QY=,iv:x8Z1zvDhkBfjWKQjpHNbr2wcfUQLsendfza0J8yfeBw=,tag:2LGd3ofcftewCBm5F4Fz7A==,type:str]
    pgp: []
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^certs|^trustdinfo|^password)
    version: 3.9.4
