server:
    name: L.O.C.H Factory
    description: Lasciate ogne speranza, voi ch'intrate
    maxPlayers: 5
    public: false
    password: ENC[AES256_GCM,data:FYHukxs9nPBs4Qkr,iv:Ui9dabwAnwgbFXHlzfAnA2ZwILkoB7+Jv1o6IFFp3sI=,tag:RLnpEXpTQsTOi0MgF/QiJg==,type:str]
config:
    securityContext:
        allowPrivilegeEscalation: false
        capabilities:
            drop:
                - ALL
    resources:
        requests:
            cpu: 20m
            memory: 20Mi
        limits:
            cpu: 60m
            memory: 60Mi
persistence:
    storageClassName: longhorn
    size: 5Gi
podSecurityContext:
    seccompProfile:
        type: RuntimeDefault
    runAsNonRoot: true
    runAsUser: 845
    runAsGroup: 845
    fsGroup: 845
securityContext:
    capabilities:
        drop:
            - ALL
service:
    type: LoadBalancer
    port: 34197
resources:
    requests:
        cpu: 800m
        memory: 2700Mi
    limits:
        memory: 2800Mi
sops:
    age:
        - recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyam1vWEdqMjA2YTF6d0RX
            Z2w4N3kxVStpWjY0VnhRejYwSGNvQ3lrK0hrClk4MjV2aUZ1enpnZzNYNU9kUnRp
            Z1lsMUVFYzA1ZnF5a3BUTzhMdHBxZE0KLS0tIC9xM2Fmc1ZSUjVVVERoUDdrSExj
            VmRzVXRQSGt4WDgwVC9jR3B0TWt6dncKK1P0NLd4DNphJk+Bs9l6AAfEzhmf4IrH
            XKHkktw8tTjfYDGHB6yr7iGZawUx5f/Jt41xnrvQmEraGL19mzD4Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T19:25:23Z"
    mac: ENC[AES256_GCM,data:ME1ge/WgB33B/GEQwAfehpw7TuQhlZ73Uf8f0UUu9IIXMwv0n8sWTrGPzeoV7kbSwZorFyCwr5xNmTeOfokqKcVoMeSd+Yj3XTY8A+iv4jAwioVs+fIQX8wDuvn137QrbMR5JpFiFQWdY0rIDfMH4xjatbG8AejBHORyIChLULE=,iv:zbpgoalTWBr7gSE3c854zHdX+xW0XHY5F0iesJiH0Ok=,tag:QQYRH8JeVTS30gQtVOAnvQ==,type:str]
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^certs|^trustdinfo|^password)
    version: 3.12.2
