server:
    password: ENC[AES256_GCM,data:JBAjd+bpNLoW8luo,iv:gzzeTrNSJhjKtg4EUGZjLoZHlUPb1PjuKVSxMSc1Gdc=,tag:+I35D6OCNtDBvNxuOH4u9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTUl5TDZrVk5lYWo4Rmkv
            Qkc4TlF3MG1qNnFiQXQ5di9HMCtySExOWkNnClZoQ1I3dERPZDF4ODhQTXk1VTcz
            b2h5T0tJYlRPdWZOVmhJMHBnbEJQd2cKLS0tIGo2QXNIaFY5NXdGK3g1ZHVDTk9j
            T3IyS3hneE5ZdWtXa3k3cUVhc1RWVDAKWZKtrrrihjQcI0t6BY7B7SdVh0eJZPE3
            qkY/ZnqTFeb+lTOuMXasl0TNMN4+8s0WchbX3XjnLE5rSSCUrUQKDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^credentialsJson|.*[Pp]assword$)
    lastmodified: "2026-09-05T15:40:07Z"
    mac: ENC[AES256_GCM,data:bMOpiplMHtbCOlIAEEA+GkfoPvBmaGC9p2oOGddXWnM+igkDB7oJWQaftvPvyX5tIme4JFmrk07wHcWe0+xKCo/amCGBjdrsEUsuW5fOOR8P7EVPsMrwCxtoxUeOnB7EYlowyvjwmJlOwAYVIc8dlVpSXsyl5uNmqb8Z660gDyU=,iv:UHeA2x8r1pcINIjdAsgqZhBLK3Sh77uOBN6azRsK2TM=,tag:JjyjG4VCMGCrzhx95ngAmw==,type:str]
    version: 3.13.3
