replicaCount: 3
obscura:
    auth:
        jwtSecret: ENC[AES256_GCM,data:KeNi7aJXeurEWOKCiKd6iRM=,iv:ke28IOrJCkpP4y56ErL4WnEG4hT8a9vq4B1qcQdSK4Y=,tag:rinSg0KOReoI9m/HmsCfyA==,type:str]
    telemetry:
        otlpEndpoint: http://otel.monitoring.svc.cluster.local:4317
        logFormat: json
    server:
        trustedProxies: 10.244.0.0/16
    fcm:
        projectId: obscura-af88b
        credentialsJson: ENC[AES256_GCM,data:7dPSxCnLs/YfBiJhYN98P0KogUFHrfMph/lPHaglwQw79PxopxoIzF1RSQ2jfNv9gWJz5hUq3RvUnzXq1iCXbc3GfXK8FAB8M5uHQyBpCOWs+Zym7mXfD4o1GNdH15QCKh4pyURNEYcyA1sDBMPTlBevBra1gq0+G3aOcH9BL+/UBCDqtZobWQJN3ZjTZCz1Erx343Ff26eF++bklagA/EbFRLtWQpFVTux+AJ+Ru1n0/AZB3IVN4vlVNpRThwvzodaHKbTia9VtYt56DuTuJ1HjlXrDvg5bcpCd+E5NpP+THwwq8R5YBlZtHPpVy8BXJiG7pyaYaDMXRdaFGQn1Oxp4GKUGSigqaRhd9LCAiPMYbQipqVkuHVQD/StyD4Wd3+Qsg6Rwgds6LCyKOWT3f/jP1f9feE2EDJrxStKWKVBaZ9s6TMMLbhy12sBRCtfd6MywGzJJyS+soYRqfYkaZdHQzydiHjSC6ajwwTl7prCQ5W+To+OwKIT0AkqqoFoWvMSpTNFtl9NN19HUFKrRH73x5SYZ0g2Q7YV4w+MOsNm4GIN1jv1fztxowtXL74ioBYgqiFkDkQJhP7eJ8F9/soHJCG6StNpfw59FxYDFYC6nWw34EoLefJTRb+F0wLpF9zHc7V5cvXsS8drzLGexpTwZyVFuIQ6zJqA1kdW+jo/d/xw0ZsJYleLOcegh+2jwjFr7V7aHRLc0lWZMU0pGp5lDn677ylod9o9mgdqiKQxf4r+JRmUzbcHhdHg5WRNtfv57GMpqcWV1ccu6FV/qtQL/tYnv2vejCMNqESN60QPE8fG491MdcDVptLHUBzQZ3zL6RfPOSjzU9s262rNKE4iWwTalqzVIYgGhkbZAi2l3R4mBzai0KN8mvTFXvhBJM0nCw8CP43ndZPeaSyIweZfkztxhQn+Tp+BTfS0a5sZTHvI1Jr+hogtrdW45rGindP8T93c3pVf1GosMm54t3mSwVqNgX86h/9Nmo2ukSQPBGKYv+jrz5mTelBty9O8Ektlo8Y1kX4pYxPaR7SNE4zRaL3QKaywKhono/SXHMag6hZ1pm0+AdNg6jWJu2wq15OrdteWLSQgWxMjjaB8EBD910v/0gQJX1cilM8VDFv6WNlpGcWJwm6Vn2wYhOd8a9wAqrN2SzR2YRZvFNGHls33OuvxpDmq2+BYatMn4kDvCgCsz34phAldlxPdU9QtPIrlzy1PieDDAo8MmEPJEA5+OmfgogOIxQvAoIuZ7m0m04/ZJ3Miq+zJHbONfvAwidoFJfpLr9NastEE403YEykrKeqrLlFhMXa6pH7dlyipRhUGVa68AY7rQE5jXy8ORHqLKHZWDEk0YtlgUV5YOfDOKG40EySjmHUhwPVueFJwyYKPcZfGRke12IXVny40ty++U/PRqDNE8Xf4b3T6FX5KOdd9nd3gmg26cxNBmpeViJ780SYaUIfNGCYhfFA45xCivsvyWbePE3i9W1UwMrkSxpipb4mDl1l9I0KKCrapryB9FVDKiHRbsXC+clhoa/+3SGTOvAaAA9AP9L4gpNEz48S6/yzvdKr1U7S2k3htVIUMNsZ/aq4KZ51C1up2q6nwFZvRTr2khwfds+QLfV0Bc/30hPvUceCXBckwBgeQU9gF67j1T2V3l1P/GV1OZanSrOWrF76EBOzHslbiP0uo49PEMf/FhKGvqUMbYqVTV1FpDg90VacW/SlBm4alDtyUCJ8z8dxxxRCXcasA6reltzljMdiBF9XAkP4wISMf/b/eVa68QWYF+jKaHRFh1OOC5s2V8hA9myNFIhuGE4pDcSRmlq7DaNqsoLrEoF7CkzMclZTusqwNmFd7/bVHAroWVIvFu83185maQcjhrHl68EY1Jm/DUJOCLSVD1k7wXxbGFmLwIzyoqIUKujdwEQ8uVGTyu6aAnibCVPtDDPs/H82C4YfSojubTzV324S+SSn0k0bpRDIzoCcw3ngIpbJqKJFafP3JdUDDdmFVMFkIzbXbWmkIJsYvwuv/8lDQgD88/upJ7aHQ/QnlVEIKlE7MNtLDuo0sik9WcuG2j1zeyZZ/FnhwoK9Ne1x59pk2pGDHTVKPfuSf2u6jKZf71sJ02DDur5FHX0wV/CC2TPsx8w2xXkKee5VEOhbcxj4oIWCjR9d/SzBwnOlCKYf3GrcCKQW2HWqEwjcuZH+PNMyYdUgTQz6NSlRkCJJDWnawQukkvD2cm1RrBeQdzk4tieketOL7io/9YkGMI5jWO0fs1OXEyTyqIzbtuY4/+H9E0LeTDRjjqakdZ2HO9KV798XHeoztiELXRs/8qM+3Gf5nhmnY1TS0P8TOFGmpkeZR2hXKwDEnLQ2kah9N158+8HuVK7T5r75Luh6olWoJ3AsJBjjx5j3h+SBtgDAE+RVwQ6kAt+XV7xbsewSJGj6LyspLLtIR75Mo+eVmlHVSrlsl44CAz9jDVtNNH7PsIXoy8M9jsjS7VwUGGASQRrXNVDoaIBUGnGU7GWh6+24oWhr/4EEx87kVEu7KfYGuA0Ock0NBYlaKDlQOXN5CtfEkD4lHqmb1fg+cpQHRiVnwSnViM53IF34SeJ368/D0ATYeaO4O8BoLkDoEMlK7xnHIEGv7xQAiP3t3XStKaLS/mK2Ma57YeD7wFndT4Z/vVHU4ZOEss7S7EBrw9QH7ZSl0FicMTdgy+O8kRgpxGvr0X5JXMZare0W9gz3lN3Uf9IO0IyX044Uwwb7rf/GDelyU7J+YvQo9VSTrSXCB1sJnrW9vAoJisqldw/urfrLRHNOq9iyTGi51wDCasYtKmHTl5Eoi14AnW8JMg9ektQU+Zp5MuhHWVx2/4N8U/GltlIzlKR1KD2p1RYGQy4yFlSfud6LTLUU1gL3awjrHR6Kyd5m9shVYgipYza/NiYkIqxE9SPqr5xNY2yPHxrgHhNSxTliLaImGUaUihmiiURLDOhR8BYyhKSDmmq4bg5LTzP+MNiJVXQ9r1Q/p5iv1rbQvK1BYtFpjt4KJvDz2tr4dngimpx5QhhAvotSmyDOCxwMh0eFvZVyszPw75cQvhTjtmOEc9yqrqGmkLMdtlBV0Y3c9gVJIfGnlqFd0dCpqGEjJvt1BD6mhtziLbxloIO1sN3F2iiVg1KFK3ajr2tyXYpZw88Qd8o12RRdI=,iv:M11LXDkUYml7VGLWzJMcfCPwZRjBm7l4YiUZHZZv5Kw=,tag:cG8ai4djYSuJozBcfpMuFQ==,type:str]
postgresql:
    enabled: true
    primary:
        resourcesPreset: none
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
            limits:
                memory: 512Mi
        persistence:
            enabled: true
            storageClass: longhorn
            size: 8Gi
    auth:
        password: ENC[AES256_GCM,data:NrZS0h2WzA5KU+ShCOtTP284jw==,iv:33jBvuIbSpC6oqCF3BKbj6IBvJcsTMSq66GkPz06g5I=,tag:f9F4MEaT4ZMIZWCvSdPecQ==,type:str]
        postgresPassword: ENC[AES256_GCM,data:K5Zgd2By8E13o4IL8mwCoH0JFlfuVkO0,iv:Rl55LhMyr9k7ox8obShFT13K3JRpasKSfSFVWgidhSI=,tag:ErQnxX8ChgtNQgvYVj5d9A==,type:str]
    metrics:
        enabled: true
        resourcesPreset: none
        resources:
            requests:
                cpu: 100m
                memory: 128Mi
            limits:
                memory: 256Mi
        serviceMonitor:
            enabled: true
            namespace: barrelmaker
            labels:
                release: prometheus-stack
minio:
    persistence:
        enabled: true
        storageClass: longhorn
        size: 10Gi
    resources:
        requests:
            cpu: 100m
            memory: 256Mi
        limits:
            memory: 512Mi
    rootPassword: ENC[AES256_GCM,data:Mh+kYoc/L0HwBCYHGqEvaAWPFw==,iv:gKdE9Lb0bK7HNxks1dz82tIVBb/cf9EFJCh+FrfBlGM=,tag:VXYGbxOWi+Eo8nhWybF6cQ==,type:str]
    metrics:
        serviceMonitor:
            enabled: true
            includeNode: true
            namespace: barrelmaker
            additionalLabels:
                release: prometheus-stack
podSecurityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsUser: 10001
    runAsNonRoot: true
    seccompProfile:
        type: RuntimeDefault
resources:
    requests:
        cpu: 100m
        memory: 128Mi
    limits:
        memory: 256Mi
securityContext:
    allowPrivilegeEscalation: false
    capabilities:
        drop:
            - ALL
httpRoute:
    enabled: true
    parentRefs:
        - name: poseidon
          namespace: envoy-gateway-system
          sectionName: https-obscura
    hostnames:
        - obscura.barrelmaker.dev
    filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
                - name: Strict-Transport-Security
                  value: max-age=63072000; includeSubDomains; preload
                - name: Referrer-Policy
                  value: same-origin
                - name: X-Content-Type-Options
                  value: nosniff
securityPolicy:
    cors:
        enabled: true
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZjhHR0FnUkxSTVNMZzY1
            ZWRFdURMVHNqN3JQQ3E4Wm9BSWFpOHBITjFvCkwrOXlJOTBOUlNOMzNxUThFTnlJ
            Uk9RMjk1U3NzVEF5VHphLzgzUXFiNkEKLS0tIERUdnNUSEw2VFFzUzVmaStTVGRv
            TmxPakE5OXhSZ2xiZ3pYK25qY2NRSDAKffUG9KxMUGmA21SuUCUsCzpCEvks6otP
            Fc39RnJjmXsaSkP46jgB7Vv1fg5XFm9ajok1J3X2MNpOpvxGK6+kYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^credentialsJson|.*[Pp]assword$)
    lastmodified: "2026-06-11T02:52:18Z"
    mac: ENC[AES256_GCM,data:lznywiMSx+0A7QHO1Z1HjRtm9ghOAlviJqk/93pBEitQOmtx/02TE7Q7csxTZ0kQoa6NFeGp65hidWngKS/WHBQhwfT99mVhijGpOYp8TGgohQ5AYSdwmx1mCH9hpxEGC1im2yxq4DaHvWVapbOpL+MOC4SC7Gkugbu4gqhNu4k=,iv:191WPwP9MgOcYYuFz+kGjqNT2AkR2U1cmqhtVekyDyM=,tag:cLoBYQZM0+v3QGXxJeJmEQ==,type:str]
    version: 3.13.1
