replicaCount: 3
obscura:
    auth:
        jwtSecret: ENC[AES256_GCM,data:eXp4mO/p4lob8GKEQ/63EuE=,iv:FSd01raj2tzPHR0lrhRlrOp+o/WjfeG2pM+nl7ULG4Y=,tag:G0rY0TboNGorFphOwjN0KA==,type:str]
    telemetry:
        otlpEndpoint: http://otel.monitoring.svc.cluster.local:4317
        logFormat: json
    server:
        trustedProxies: 10.244.0.0/16
    fcm:
        projectId: obscura-af88b
        credentialsJson: ENC[AES256_GCM,data:OFLjneS0smXbxLHw59ZeGH16PyMEPmtw6IOD0auTS/brVpgc1yqTbKgfa63kRrT1S5Ib4hW55oh2R/rLSB26QA2I8NUUlSh0LDf1+R6ZwzEeNHBNjDdpcA5yBDCk3iOyOwW5LjwA/OnXMUHHnrTGmkT7XtzonMtNw2g3q9IRIZAggVCK0gD73Kq999QxlhYnW8zWEgMSvQJIHu7lnGRvyFGp/3FIXMG0Rvh+5LWZOgenCPGOK5HXLzo3LuxF5PmGf4SQvUd24X7Sd9vqyI5UIcCpw8D25xVclD86bRH8KA6f5XLepLJY1iS23TtaHiNigYZzqlOaUqSa6kUuY+EEobllkkp8mzuD01tq1bBLD1cAghL0mVh6rJbK3LuSVXDmnZ9+8n3hA6NZZt9YlRDrUhqSo2t0wwPr/2/Vu7zbOzgl7bmV5UAJw5XU6gGzFtZgFz6b2TcXDvJANuc8hYAeTi6HZgtmz7bp7gFiDJF+E0Z6GNnWf2RhQCPca8iElr73Ei91TSDmFAeOJUekpJJ/enCZuf1Et3NQxkpW/hjYKekQ9qwwskkz8WnJKCNpM/H0RKWKgHfCKx0qeAE7itBz7VJ8QiWDVB3wWDAI+tK+UWUxK8Laeeloaiy3kdNGJGCYPrCwAyjT5ZmxDCGiMBNHpEaGt0keZudzkUnlXc3nMxjO4bNhC/YLuemj1roCRiqgOsRngsQlEzb3wSPkm9Bl6zdQh8C4C5qZx+ZJtag72sNkEQemkgfB42U2PP3OiPzqJpY0D96IZifMWUph4t8tOWvHb3BgLsenwmp+1CO4hscIPFU++7yt8sZdo5O1XBrQ8hsyDgW63d/y46INA3RtXbBB6Bfj50PUHpKdhRwHDxCpghIIFp0PtFNW1jvZXZDaFjH+mVdIJ0jbgbor4NF4vmRPir5bBsGRMVgS0B7Wh1mT+LQJQvseF5mqc101yjTScDLxObuvF6ieuknVJA7sLu2+x/21ynC/W9cSYCJusdMoztW6tn226GETt9ls/bmfOKGZdjGC4gyt4XvjSOa3RpTn9SPqy1UkdHY/D17INvPp43PcjmTqjto9oHpwa6w69VMHz+Lf/yaGjrzGaKUXq7RxcD72KBucb28RigzX0Lyt8maYN/dAF/sB826Viy7lZXtOsqBTp61WoxMhA4d2SaUkV3quSVu9Ite97ZBcU8Jv58/nLLH77FCvFiOGbg9DuKg7WQk/o/zsTy7nsqJu9BeaLr5TUv1Ey1TBYM6eqFtV574DI3jW19W0hHDwph69xGEnGbjWZo9kLLmvJWq/CojedKrwxMhZmmIjrpiEmFgY4O4KjeEOyKv8vlzhykiXOjsAUqi+rutpsHvmXFME9tfin8/dun2KpzBuT0nQ7RMnAYcSFSYnlRRajKCClAWBcSoxG2sUuI0sPmFN3D3EnvB4x2PT8nwj/WBndRWAeQmmmHm6y0vMmUCUUp0KtfK0V8VEKnXPgSiWrYB3FWWxMgKR3u04hvH3w92m+Vdi2stFJvVx16WjpRTw8rpuXBqxw6fS3hfLBLgGfsB0IbHxA5zZsxRwZImaAo9ceQu9mbw4QBuYVqKZoKJqTx3wk5DpqFIIUnfnFofgi7vjt8COE0WwatZdL4xtz5FwbrlD4SUV3xyLl//Z1A9q56r5scESdzpcjOiztdWj2WJZlGp19PTCesH9LSPWpvXp8KZNCnYOpLtFG9oMrr4IKIOgWTMKNeGnwDDt8+24M1av8UbYwAjMFgT7419ziG1S1iw9tp2hxpGQWVN/JU8SAhhGtk7HhiqHPIwkjrlgmLvpStwSGjQtjOIQPepv2jr+741Xd4nKC2EclHWwOUvEuG7CQ3/kX1xZ8N3B8l6nNF8mqqve1S0iLFQq1rj2PRcw0b1zYy1FvnWSCe3wb36tXx4yJYt8Iu/octOFVUffvglipGnT4CxH1LXu8PL13olNFgwPLo1d6vq0spMai8AB6JzalhlqyghsaTk2g++U5Tq44K4s8JRD8k6Gqi7QDKwY+2ATy59E/99KLjZg1pmP92FXdsR3It3AkBUYXQAF1ukiErbZh7Rg0Pj8Xgv/qcCahossBIfsvcJvWnD8UInke1X8lxv6wIEymR2SANPg5565zAQLwo32L1KdFTIx0LMaRx8+w6lJwsbwP+X+bh4yua7bbBMQuhQ+qGn6Yad7iExbiJRsssY3NozJJ2xmzeyvq+w5cJLygQDKSRRKOjbMSeBz3WI5DEINNOEqw/dH2wUKWlmriHFSaFzPFPTu97ZL63EUTXF1zNM8Q4NKzEwFk0FIEekRQZjkVCMMwpVGlAlptSn3wilm53hVVzr+boJQjLgDmFnhxGsXihPY10yee4221HCJYTLkzzRSfxlXlK8SkKCv/K9IsBKG0zxXNz5LlbQAOpPevFHIGyi3dgkYBcTunyLO24iyTHDiF1xcjaJhh8z0uD6mdaqanC7yOl7Se82c/Pcc55vpHoUVm4RdRJtba7YZJFQaLbbg9ZbLCxmFbgTltdeSWsyrZE4VEitFYfag/sfbVosEFAQWVA/Mdo/iMTyyN4cstGGBChelswtXSPeQXSzJ7L4BaUXs/dCi69YdGmplZs/K1hxHSCojcIwRvXuBLMuZ/ohDHu+Djbsn8bjZg2ikmSAhBhzDW1LMt6p8Rn8JbRpfayf+buDD/XqixFPVJErBs3QknA2A1nOaAtaNDJVzJtE80KDH78EXg3X+JdW6cdufNlOd68wnVs2VjQKFA4IC00bJVPh4alwB3jO8b9LgUZEOA9pRaIfHjkkWrI5Vo+A69pHcRuEfcWbpSIZ84HsvCJ/2x52RYAMyPbgUMPJnYg7+hNIFA/ZEcBOYmngT5ikYfkaIdrYZVUH1RcrlnIE0sCourYZwIo2P8D03qT/RqfvN2OuhXG6LGzyIRsliAi+3DoTA5m8aDeiEZe9UzDmiJdPWd1AFVIUvK2RIG+/5utR5gsthimwQfQAFHT3ivNrVGH5R30iJ0TW7RSEMKH1cMTFE7f2FfdN3RXcSbI3yztKS8LVEadJwAEDGPP27KFUydXOYqkRriXedZlN3wjHfSHsXoOAtrxeotW2Oy5auEuccbubt1kkSEbNcW4f7KUUXcCjm1E/LqlFQTjF0BAtXrjIkR2WXMTxYHSpnHcUO3fbqI2U5CNU=,iv:0MOwVGqgCIafeeBQKSYz0yNAQreDUf3km53XZE+Mj9k=,tag:BUV+EQ1mo2qGtJT8DGoxnw==,type:str]
postgresql:
    enabled: true
    primary:
        resourcesPreset: none
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
            limits:
                memory: 512Mi
        persistence:
            enabled: true
            storageClass: longhorn
            size: 8Gi
    auth:
        password: ENC[AES256_GCM,data:2PUBuSi++Iu/frjKkW+0R2cO5g==,iv:3jQPs+Sa45Sqr38DlzNrx8LU3K6dDHib+6J65aKGrd0=,tag:LLAzJxgfA3/iiBuVCOwRdA==,type:str]
        postgresPassword: ENC[AES256_GCM,data:KWm+FTEnH4uOQq7woyQ5eqmb66Q+nE8l,iv:2/IzOG26nLzXSjlH6G5e4kAFIqe7kJEyxIVraHjzt6M=,tag:EZP1M9KChVPn3Qa6PGTu/Q==,type:str]
    metrics:
        enabled: true
        resourcesPreset: none
        resources:
            requests:
                cpu: 100m
                memory: 128Mi
            limits:
                memory: 256Mi
        serviceMonitor:
            enabled: true
            namespace: barrelmaker
            labels:
                release: prometheus-stack
minio:
    persistence:
        enabled: true
        storageClass: longhorn
        size: 10Gi
    resources:
        requests:
            cpu: 100m
            memory: 256Mi
        limits:
            memory: 512Mi
    rootPassword: ENC[AES256_GCM,data:sZ0e2A/IhuQIVs6JagCxSMLOfw==,iv:x7+9lgiMZnk66oVqfXAvUqmzIO9uUYoooVIilpY+5SU=,tag:LR0nNZ1ISxb3UwC0+Vd0DQ==,type:str]
    metrics:
        serviceMonitor:
            enabled: true
            includeNode: true
            namespace: barrelmaker
            additionalLabels:
                release: prometheus-stack
podSecurityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsUser: 10001
    runAsNonRoot: true
    seccompProfile:
        type: RuntimeDefault
resources:
    requests:
        cpu: 100m
        memory: 128Mi
    limits:
        memory: 256Mi
securityContext:
    allowPrivilegeEscalation: false
    capabilities:
        drop:
            - ALL
httpRoute:
    enabled: true
    parentRefs:
        - name: poseidon
          namespace: envoy-gateway-system
          sectionName: https-obscura
    hostnames:
        - obscura.barrelmaker.dev
    filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
                - name: Strict-Transport-Security
                  value: max-age=63072000; includeSubDomains; preload
                - name: Referrer-Policy
                  value: same-origin
                - name: X-Content-Type-Options
                  value: nosniff
securityPolicy:
    cors:
        enabled: true
        allowOrigins:
            - https://*.obscura-client-web.pages.dev
            - https://obscura-client-web.pages.dev
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NTcwaS9iYktkVzdyQmVu
            ZFRrN2p0L1ByTVM0VU9ackYvbXZLU2tIbkVVClpMTy9JUWJ0Q3liR3JOZnhsQXR3
            NkFvemNwVkk3elE1QWZ0WEx0bW9LZDgKLS0tIFI0R09VS3FxSHJ3WjMyWG82UHQx
            bTBmaFRNYWtuL3VTemd3VGF6THlucWcKInfYLwLxYRZg+UU8qXZ99GvTgLtkmPwu
            yOXNaQOfa4G4DJFYSGEhhS3B/i1HMMp+nfEegQOUpLwgadr9bbzDfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^credentialsJson|.*[Pp]assword$)
    lastmodified: "2026-06-11T03:31:54Z"
    mac: ENC[AES256_GCM,data:PSZu8cP36LoRhNpEt6YuUlrYQbT9b0Ik8KaLCgOMXOJ6L47NShTsUrvG0zet9gOAVvHNdoiDdh0hb6QKkFU8whB3N53wLeomP5zFbMbsqz1JlJu9UgBUvUjWs+WnvNes7/i1HJshXbUTfRXik0y5Q+2P/3WKjXfr+6zn2VyIDXs=,iv:Zk0ozTrVWWrXeBe5gsjPbX/6qJl6BejrbbnedQ2GddQ=,tag:thTjDndbp+ynfmB9WdGGTA==,type:str]
    version: 3.13.1
