---
pistachio:
  ups:
    host: pollux.lan

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 10m
    memory: 5Mi
  limits:
    memory: 10Mi

dashboard:
  enabled: true

serviceMonitor:
  enabled: true
