---
persistence:
  storageClassName: longhorn
  size: 20Gi

satisfactoryOpts:
  maxPlayers: 6

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

service:
  type: LoadBalancer

resources:
  requests:
    cpu: 1000m
    memory: 7500Mi
  limits:
    memory: 8000Mi
