---
persistence:
  data:
    storageClassName: longhorn-local
  weights:
    storageClassName: longhorn-local

securityContext:
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: chat.poseidon.lan
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    memory: 500Mi
    cpu: 700m
  limits:
    memory: 2Gi
