---
serverName: Barrelmaker
worldName: Asgard
public: true
metrics: true

persistence:
  storageClassName: longhorn
  size: 10Gi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 111
  runAsGroup: 1000
  fsGroup: 1000

service:
  type: LoadBalancer
  port: 2456

resources:
  requests:
    cpu: 700m
    memory: 3000Mi
  limits:
    memory: 4000Mi
