serverName: Barrelmaker
worldName: Asgard
public: false
metrics: true
password: ENC[AES256_GCM,data:+TYDz0gvj3a/bQ==,iv:35Sts08Fv4Q4O6UOaHDgA64kM0aWYBBRTkf5nJzf5TE=,tag:BqLZ4Rh2jO7nx2erdbp6og==,type:str]
persistence:
    storageClassName: longhorn
    size: 10Gi
podSecurityContext:
    runAsNonRoot: true
    runAsUser: 111
    runAsGroup: 1000
    fsGroup: 1000
service:
    type: LoadBalancer
    port: 2456
resources:
    requests:
        cpu: 700m
        memory: 3000Mi
    limits:
        memory: 4000Mi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydkJKQ0FEZTFCWlpnVmsw
            bFRNck0xOTZacE1WSWNDSXV3ZE5QVm9EYjFRCklnRnJyZ0FPcEZjbzg0M3U2UmVm
            OURzTjJNYnBGU2UvRXV2REhkRXloK1EKLS0tIEdld0JPZlBPNjBLb2w1Z01Rd1cw
            emI5RmdsZVdDZCsyS1RmLy9pclRpc0kKpqbAKtCkYDdb/EbWzoTH3DWrHYKm9ecH
            t/OQs3p2XbUabXmfinUQBH3E0yz723UYirkJ/ndVYdHNT7OdybtxFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-16T04:29:24Z"
    mac: ENC[AES256_GCM,data:E1Wyn4OcXUBcNGsrVoQShE50J8gPjNlk9eZc3/YMbOJ1RwMS9HJ5t8iUYaLtMJyWofBRz2SneXwd7IuWXu9Mi3BKTKc6mie3pBgyFqpiWD7UdHFK4hFZgkw4sb8mRk1p3w2Yu6qaIMujqS17lADtPnrtjPLlBOnFRNK4jrpOXZ4=,iv:n8kvmFyCJ6gCbGk9ZMpglc84hz2iflfEW/Zd3jTnOco=,tag:CinfLQaRq6nLUN6GlksRwg==,type:str]
    pgp: []
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^certs|^trustdinfo|^password)
    version: 3.9.4
