---
gitSync:
  repo: https://github.com/barrelmaker97/website.git
  ref: main
  contentDirectory: website  # Directory in the repo containing the site content.
  periodSeconds: 60
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  resources:
    requests:
      cpu: 20m
      memory: 40Mi
    limits:
      memory: 80Mi

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header Content-Security-Policy "frame-ancestors 'self'; default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self'; base-uri 'self'; form-action 'self';" always;
  hosts:
    - host: barrelmaker.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: website-tls
      hosts:
        - barrelmaker.dev

resources:
  requests:
    cpu: 20m
    memory: 600Mi
  limits:
    memory: 700Mi
