---
gitSync:
  repo: https://github.com/barrelmaker97/website.git
  ref: main
  contentDirectory: website  # Directory in the repo containing the site content.
  periodSeconds: 60
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  resources:
    requests:
      cpu: 20m
      memory: 40Mi
    limits:
      memory: 80Mi

replicaCount: 2 # For faster failover

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: barrelmaker.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: website-tls
      hosts:
        - barrelmaker.dev

resources:
  requests:
    cpu: 20m
    memory: 600Mi
  limits:
    memory: 700Mi
