{
 "title": "Nodes",
 "tags": [ "HomeLab" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load5{job=\"nodes\"} / (count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"}))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 29, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1-node_filesystem_avail_bytes{mountpoint=\"/volume1\", instance=\"soteria.lan:9100\"}/node_filesystem_size_bytes{mountpoint=\"/volume1\", instance=\"soteria.lan:9100\"}",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "1-node_filesystem_avail_bytes{mountpoint=\"/\", instance=\"pollux.lan:9100\"}/node_filesystem_size_bytes{mountpoint=\"/\", instance=\"pollux.lan:9100\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"nodes\"} - node_memory_MemAvailable_bytes{job=\"nodes\"}) / node_memory_MemTotal_bytes{job=\"nodes\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp1\", chip!=\"ieee80211_phy1\", chip!=\"ieee80211_phy0\", job=\"nodes\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}