apiVersion: v1
kind: Secret
metadata:
    name: obscura-valkey
    namespace: obscura
    labels:
        reconcile.fluxcd.io/watch: Enabled
stringData:
    password: ENC[AES256_GCM,data:tep3BVgzLWsxG27UcAPHyCZr0/zuWWSQ4tbo+6bTP9o7/6hU50N+q++Sebe01HHX5LNOrnmj8cUdRcoNxyrcgw==,iv:SDkHPi3SSI06WlMxiBfAv63cb7wQmEp7gtWAkPjvfqE=,tag:UV9IMrJO5xd3QywFc95VeA==,type:str]
    url: ENC[AES256_GCM,data:bUF1XXMwEiLXGDpg6RegGZPw8YSTuMhIGGlKSCAcFPeOxFkn9HapoIpPvd0g7TuU+TkyDYbdU2/hBoIImHPv2JzXWmUJaaGOnSsYxYIR+d/Gv54r3w==,iv:0C6e+6ffpexOJxnodqXIG1XoiMEDYK7+s0LUWsikYk8=,tag:qhfUNwk5RWndRUSbh5Gf5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZlFsZ0Z5czFLTE55WTFa
            WEdKTmhxYVRDZWpkc0V3VGt6c1NDeVViRVZ3CmttNFZJRk0xMHlISGw5VjdWM25Y
            cytpM3JkNkxzZkVlZG9CMCsxcUl2Q1UKLS0tIEJPWlI4aVN5a21YSWFsdmlQZ1l2
            TjJpakljL2tySXhPTm91RTh4SldTS28KNZXT0C0C4O7YDZ0sp+bCFsZygQTgq9QF
            wO5vhf2Wlngn7nu2ZNWhJNeno5eR/9QVxcGy/+yy6fwE3NuOWJqUiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHck4ydlRYbThhdVhSU3ht
            SFFOSFBJM3RjdThKTEF1NXJka2NTRFNsMndVCmVPZGFEbHpHT05yOE41TXo2QXJ4
            djU3MkNuSWRzOXNNbmswRkh0Z3ZsRWsKLS0tIEc1N0xsU3NhVTlaTGE1MThEUWRW
            UnBLNWI5QWZ2c0VlV0xCRVkyQksxSFUKdXYMa4HntFcfrKKP0Nzwt4sdkhVwoKHm
            oP+gcMtYpzT7ZuGupFSY6OHf4GQ+sXqUujqNmjhT+K3sbSFF6ObE2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d70v7e0uyptut9mjuh06zsdt7udslentsp3ernvtwhemnlgz6s3s2587sr
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^credentialsJson|^secret_key$|.*[Pp]assword$)
    lastmodified: "2026-10-10T16:33:03Z"
    mac: ENC[AES256_GCM,data:5LMomD3znyRW3XdMhwMeRyyibw757J6KYkQD0F/dnrbVLvIInUOwbnsK8KBEp73ILH+HXQn9lnJaD4bZKvsG+GT4/wxh01h1ZPLP20ZATh4mfGhLKKffcLu9rd395i+/RktfuD8/WVsgrhCo+bAfshv/odFJ/DFAJe6lcsWgiGs=,iv:Nq5rBNhb9BKTaRaUNiSlWvUrEYdejHtXbCDX4Uc1sbM=,tag:x8f2zIvk2uOKF//QXbMziA==,type:str]
    version: 3.13.3
