---
- name: Create User Namespace
  delegate_to: localhost
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ cluster_user }}"

- name: Create User Cluster Role Binding
  delegate_to: localhost
  kubernetes.core.k8s:
    state: present
    template: clusterrolebinding-user.yaml

- name: Create User Resource Quota
  delegate_to: localhost
  kubernetes.core.k8s:
    state: present
    template: resourcequota-user.yaml

- name: Create User Limit Range
  delegate_to: localhost
  kubernetes.core.k8s:
    state: present
    template: limitrange-user.yaml

- name: Install Helm
  become: true
  community.general.snap:
    name: helm
    classic: true

- name: Install Helm Diff
  kubernetes.core.helm_plugin:
    state: present
    plugin_path: "https://github.com/databus23/helm-diff"

- name: Add Helm Repos
  kubernetes.core.helm_repository:
    name: "{{ item.key }}"
    repo_url: "{{ item.value }}"
  loop: "{{ helm_repos | dict2items }}"
  vars:
    helm_repos:
      # bitnami: https://charts.bitnami.com/bitnami
      barrelmaker: https://charts.barrelmaker.dev

- name: Deploy Helm Charts
  kubernetes.core.helm:
    name: "{{ item.key }}"
    chart_ref: "{{ item.value }}"
    release_namespace: "{{ cluster_user }}"
    update_repo_cache: true
    wait: true
    release_values: "{{ lookup('file', 'files/{{ item.key }}.yaml') | from_yaml }}"
  loop: "{{ helm_charts | dict2items }}"
  vars:
    helm_charts:
      ingress: barrelmaker/ingress
      factorio: barrelmaker/factorio
      # gmod: barrelmaker/gmod
      jellyfin: barrelmaker/jellyfin
      niucraft: barrelmaker/minecraft
      # serge: barrelmaker/serge
      # valheim: barrelmaker/valheim
      website: barrelmaker/website
