---
- name: Create CloudNativePG Namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cnpg-system
        labels:
          pod-security.kubernetes.io/enforce: restricted
          pod-security.kubernetes.io/audit: restricted
          pod-security.kubernetes.io/warn: restricted

- name: Deploy CloudNativePG
  ansible.builtin.include_role:
    name: helm
    tasks_from: deploy
  vars:
    helm_chart_name: cloudnative-pg
    helm_chart_ref: cloudnative-pg/cloudnative-pg
    helm_chart_version: "{{ cloudnative_pg_chart_version }}"
    helm_chart_namespace: cnpg-system
    helm_chart_values_template: >-
      {{ core_role_path }}/templates/values/cloudnative-pg.yaml.j2
