---
user_kube_dir: "{{ ansible_facts['env']['HOME'] }}/.kube"
user_key: "{{ user_kube_dir }}/{{ user_name }}.key"
user_csr: "{{ user_kube_dir }}/{{ user_name }}.csr"
user_crt: "{{ user_kube_dir }}/{{ user_name }}.crt"
user_api_crt: "{{ user_kube_dir }}/cluster.crt"
