customization:
  systemExtensions:
    officialExtensions:
      - siderolabs/iscsi-tools
      - siderolabs/nut-client
      - siderolabs/util-linux-tools
      - siderolabs/i915-ucode
      - siderolabs/mei
