---
storageClassName:
  config: jellyfin-config
  media: jellyfin-media

resources:
  requests:
    memory: 500Mi
    cpu: 700m
  limits:
    memory: 2Gi

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

podSecurityContext:
  fsGroup: 1000
