---
persistence:
  config:
    storageClassName: jellyfin-config
    size: 1Gi
  media:
    storageClassName: jellyfin-media
    size: 50Gi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

resources:
  requests:
    memory: 500Mi
    cpu: 700m
  limits:
    memory: 2Gi
