---
serverName: Valheim
serverPort: 30005  # Must be in the range 30000-32767
storageClassName: valheim
worldName: Asgard

resources:
  requests:
    memory: 3Gi
    cpu: 700m
  limits:
    memory: 4Gi
