---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: factorio
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: factorio
  local:
    path: "{{ local_storage_dir }}/factorio/factorio-data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "{{ local_storage_node }}"
