---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: jellyfin-config
  nfs:
    server: "{{ nas_domain }}"
    path: /volume1/local_only/jellyfin-config
