machine:
  install:
    disk: {{ install_disk }}
    wipe: false
  network:
    interfaces:
      - interface: {{ interface_name }}
        dhcp: true
        vip:
          ip: {{ cluster_vip }}
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
