machine:
  install:
    image: factory.talos.dev/installer/{{ factory_response.json.id }}:v{{ talos_version }}
    disk: {{ install_disk }}
    wipe: false
  network:
    interfaces:
      - interface: {{ interface_name }}
        dhcp: true
        vip:
          ip: {{ cluster_vip }}
  time:
      disabled: false
      bootTimeout: 2m0s
      servers:
          - {{ ntp_server }}
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
