---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: obscura-postgres
spec:
  description: "Development PostgreSQL cluster for Obscura"
  instances: 1
  enablePDB: false
  postgresql:
    synchronous: null
