apiVersion: v1
kind: Secret
metadata:
    name: obscura-valkey
    namespace: obscura-dev
    labels:
        reconcile.fluxcd.io/watch: Enabled
stringData:
    password: ENC[AES256_GCM,data:LFSl94P43pFdElZVJthnvcO/3nuiBn5xVEUlorn/wURDHrAB8uYGYtEq5x8VfvIGSRrQ9l2ui1MITrIhN7JMWA==,iv:8mjMW8JNSA1qgES+J3WfTvcQnRCBYymERJOsiZAKvR4=,tag:3BY5sUrLbuuEtYtfxsOJiA==,type:str]
    url: ENC[AES256_GCM,data:9caatjEo33M1nmvESgn9rFy9Vsrv/tz7UftKGf21YGB0E3Dq6J2EJPDWpfcsoBK3W9erK5T/3G8JK2DtEMp5LJXIE2Z7n28vGpszYtFsXWxU92zFzw==,iv:GhILEPrqApKdar9w/XSux5xKSzovQ/HJvTtqR9qWbrY=,tag:UXKZZ1Yuk960H/XH4ISSyQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMkZ0aTdvb1pFejVGQVQz
            SENwMFAwK3Z0akFyME13TGErbEgxWmI3VEdNClVQKzJUZzNST2RuRDZwbkNibzVH
            eEk5bkJ1ODBsV3RiZGdId1o4azVjQlUKLS0tIGZMMkZDZ3prbUtGQk9uU09ZUWYv
            Q2ZwT1BOYnRUWkdRZU5RNXJ0aXZPY0UKzBThVB7DatwM2zQD9ucqD6Ab01+jGego
            ugPCdPPcfXuLD8u5jJn/qccSVE3qJFbtY9douVAE+QoA5c2+EcfzRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySmY0ZzBzNHd5YVZ5SVVV
            T2JyTDFScTFjVFZRUjROeldtRy8rTmFaaFFVClNDRndNVEN3L1k5VlhPNXJPWjNJ
            WHhWUGR3VnQvUSt6SDBhZzc5NTByL3MKLS0tIGZIL0F1QnhpcTVpbHJNYUN4WVFm
            OVVESnJITmRsb1YyR2hxVDVFU3lKL1kKUCDEU0S7Er+6cqmT1pDJaU4069EwLnMV
            8UjuJPFCubP9+cxYFrs7hIvZp2hLczYfgVtoQ/4VCaMg0/lT7P2cKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d70v7e0uyptut9mjuh06zsdt7udslentsp3ernvtwhemnlgz6s3s2587sr
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^credentialsJson|^secret_key$|.*[Pp]assword$)
    lastmodified: "2026-10-10T16:33:02Z"
    mac: ENC[AES256_GCM,data:JO7/0g7FkubwsSEsPoBWQLtJGNaY9edMLeoLQ+punndJamOwWn4p3bsrbwAcQposOkmI+/OiE9WWtm6/MVQkRoUuKtPIXioIQ96FbcicH/kEyy4B9X262+pbBS+7+elFG5AFaNKw52Gsw9AIqVOE1LglSnEJeb0RgKgnKxyY+7o=,iv:jKWNJH/DHxMKB3eKkMhRAnhCJ+MfA6A2kFs8FffMDns=,tag:vmqRLw5PjSSiRz41TOWbng==,type:str]
    version: 3.13.3
