---
- name: Get Talos Image ID
  ansible.builtin.uri:
    url: https://factory.talos.dev/schematics
    method: POST
    src: customization.yaml
    status_code: 201
  register: factory_response

- name: Print ID
  debug:
    msg: "{{ factory_response.json.id }}"

- name: Download ISO
  ansible.builtin.get_url:
    url: "https://factory.talos.dev/image/{{ factory_response.json.id }}/v{{ talos_version }}/metal-amd64.iso"
    mode: "0644"
    dest: "{{ ansible_env.HOME }}/metal-amd64.iso"
