---
- name: Install python-kubernetes
  become: true
  ansible.builtin.apt:
    name: python3-kubernetes
    state: present

- name: Install nfs-common
  become: true
  ansible.builtin.apt:
    name: nfs-common
    state: present

- name: Install microk8s
  become: true
  community.general.snap:
    name: microk8s
    classic: true
    channel: "{{ microk8s_channel }}"

- name: Add user to microk8s group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: microk8s
    append: true

- name: Wait for microk8s to be ready
  ansible.builtin.command: microk8s status --wait-ready --timeout 1800
  changed_when: false

- name: Allow packet forwarding
  become: true
  ansible.builtin.iptables:
    chain: FORWARD
    policy: ACCEPT

- name: Install iptables-persistent
  become: true
  ansible.builtin.apt:
    name: iptables-persistent
    state: present

- name: Create microk8s launch config
  ansible.builtin.template:
    src: launch-config.yaml
    dest: /tmp/launch-config.yaml
    mode: "0644"

- name: Apply microk8s launch config
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    snap set microk8s config="$(cat /tmp/launch-config.yaml)"
  changed_when: true
  args:
    executable: /bin/bash


- name: Wait for API certificate to be ready
  community.crypto.x509_certificate_info:
    path: /var/snap/microk8s/current/certs/server.crt
  register: cluster_cert_info
  until: "cluster_cert_info.subject_alt_name is contains(alt_name)"
  retries: 12
  delay: 10
  vars:
    alt_name: "DNS:{{ cluster_host }}.{{ local_domain }}"
