---
- name: Check if secrets exist
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/secrets.yaml"
  register: secrets_file

- name: Generate Secrets
  when: not secrets_file.stat.exists
  ansible.builtin.command: talosctl gen secrets --output-file "{{ ansible_env.HOME }}/secrets.yaml"

- name: Get Talos Image ID
  ansible.builtin.uri:
    url: https://factory.talos.dev/schematics
    method: POST
    src: customization.yaml
    status_code: 201
  register: factory_response

- name: Print ID
  debug:
    msg: "{{ factory_response.json.id }}"

- name: Download ISO
  ansible.builtin.get_url:
    url: "https://factory.talos.dev/image/{{ factory_response.json.id }}/v{{ talos_version }}/metal-amd64.iso"
    mode: "0644"
    dest: "{{ ansible_env.HOME }}/metal-amd64.iso"
