---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valheim
  namespace: barrelmaker
spec:
  releaseName: valheim
  chart:
    spec:
      chart: valheim
      version: "0.5.3"
      sourceRef:
        kind: HelmRepository
        name: barrelmaker
        namespace: flux-system
      interval: 1h
  interval: 30m
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 15m
  upgrade:
    cleanupOnFail: true
    strategy:
      name: RetryOnFailure
      retryInterval: 15m
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: Secret
      name: valheim-values
