password: ENC[AES256_GCM,data:+TYDz0gvj3a/bQ==,iv:35Sts08Fv4Q4O6UOaHDgA64kM0aWYBBRTkf5nJzf5TE=,tag:BqLZ4Rh2jO7nx2erdbp6og==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlaWxTQ2d4b0pjWGNVNDBa
            R2N5Vkxod1VjbkwweW5qc1RZT2NuQS9LeUhvCmFCTEx1T1JpS2RVeHJESWV1Tmpt
            MzN1T2ZPa2V6R2RIKzNBRXl5aVpvQWsKLS0tIHdHMXlNY0Q5NGduNFdLRENGOXBU
            OU9NQSswRVRYZlhqN0ZFZ3hoMy9ucUEKHe9FKnFFyGTbA+SWNBSHYNBOEchQCoMh
            bccmVU3i7JwEVE8pgO6ZxDjquB8YoJOqDWc5RCCjautBFMLnwsYPdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVE1STTA2aUdCZ0tBUE94
            M0p2TGg0cEJQWTVJYXAzRFRkWmkxVDdxcUh3CmNZT0dFK1ZSb2FUcDBuTitybms1
            Z3h1WTgwMjZ0N3p2SVZXaHBqcHRlMTAKLS0tIFZ0MnQwUkZWNVF2Y09QQ0lyL3V4
            and2azhVZlJLS1FsZHpZM2FlZm5KUVUKCwyTqaM9k/C7mIKL+jl/ZtBql8IVPvni
            ixhvyP9kCgIBVBzDZwvqVVfEn8CRSM6uqQeBqX/BHK5pFdC/x3jYtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d70v7e0uyptut9mjuh06zsdt7udslentsp3ernvtwhemnlgz6s3s2587sr
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^certs|^trustdinfo|^password)
    lastmodified: "2026-10-06T22:33:02Z"
    mac: ENC[AES256_GCM,data:isNHbMVe+PMKWI3Ukm45kluuQXKBMVorOLzdSYGMndrlMBrrZ2MxpFrONNwmagAl3e60sst+BU7aqz+IOWdoJ/zYIxNPJM0HrAHkaTcT5mNhibZDPv++tOBYCwlxqn9BjtAAw1s0gsbOt9xPs69W/fY1HwcHSEJB+hmQ2Mfg1lg=,iv:RpWoU2rWazN5Y9RtAVB40XsDP3IaJxWy5X0vovuGhao=,tag:o1R5Qv9jU7wjzw1PDdP5QQ==,type:str]
    version: 3.9.4
