---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-proxy-config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        container:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              minDomains: 2
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: proxy
                  app.kubernetes.io/managed-by: envoy-gateway
                  app.kubernetes.io/name: envoy
                  gateway.envoyproxy.io/owning-gateway-name: poseidon
                  gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
              matchLabelKeys:
                - pod-template-hash
      envoyPDB:
        name: poseidon-envoy-proxy
        maxUnavailable: 1
      envoyService:
        annotations:
          metallb.io/loadBalancerIPs: 192.168.15.60
  telemetry:
    metrics:
      prometheus: {}
