---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gmod
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gmod
  local:
    path: /home/barrelmaker/gmod-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "{{ inventory_hostname }}"
