---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: valheim
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: valheim
  local:
    path: /home/barrelmaker/backup/valheim/valheim-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "{{ inventory_hostname }}"
