apiVersion: v1
kind: Secret
metadata:
    name: internal-ui-basic-auth
    namespace: longhorn-system
stringData:
    .htpasswd: ENC[AES256_GCM,data:jDCGmhdk1rhDSU5WnJzHZ/9n7NkHDoFL+HSyqO6vBtYuPIq/XvIj,iv:3Zdegzh38MCgyGL3CBx9Wt4dqMd/GmdIoR880wk75TY=,tag:iv7omaeOZRaFn7Y9Sip8QQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTTdGMGJaenhSMjRnYTQx
            Y21PVjhpb2czVHpBdTkwMkNPdVlwanZPTnlVClQ5elhBeEphTVcxUHpNZ0g5cyto
            ZGp3bElOOXd1dnZBWlc1OUNJTFVrZEUKLS0tIDhHK0w0OEdyOXhIanBxWHpxR3RM
            dnJoMUdIYW1XRW5TMjcxQm84QWltVlEKUkeF1DhP/HCGK17WaP52ezJfdUhcp9XY
            zkw9LnoGTPUKCHXTvjELDWIOqAtzX/ScPjjMGwtySus7ttRAi8xdaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWTIyMHdTQXd4YzdOK0Vk
            M2IxNXRRVnVLKzJMTWRuTXg1OWc2NzdvSVJZCnZLZllFcEtmSVMwZEhVeEpWWDZD
            L2hJSjNpRk5WQlY1TEJ4UnhYUVNEZW8KLS0tIFRpQVZzSzhrTmVVZUc2TEN3TzMw
            RTRTY2ZnZWloRTdGYlhTU1lZMjE3YUkKeCycCIe5C2VSZdVxkcCiYHVfBnNb2hd9
            r+goyv2RoKeF9wi6GOMPASS6HccCBPxKf7PsqK5O7RpwqsCWqv9uhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d70v7e0uyptut9mjuh06zsdt7udslentsp3ernvtwhemnlgz6s3s2587sr
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^credentialsJson|^secret_key$|.*[Pp]assword$)
    lastmodified: "2026-10-03T14:52:41Z"
    mac: ENC[AES256_GCM,data:3hhbkRRSVDDX/K5o/DFJ81ognMimITvIXJuC7AIHED2jFmVnmJNbPw6s38UivgX4vTLm0uBR0oFy0hqMFLM1DQK7QmJHLY0h2APRXVP42APp8a1r6zhZVk6dh34XSIhPzzZmTM6gjlLoRVlptP77TguMhxcw0HiWLxEdgIGq0Dk=,iv:fahtKEayW9qdHOjKsSMgp2nXIUj7tgzpCjpVTZsXEtw=,tag:FMiGf9F1dVzgm209xnE0Gw==,type:str]
    version: 3.13.3
