apiVersion: v1
kind: Secret
metadata:
    name: internal-ui-basic-auth
    namespace: monitoring
stringData:
    .htpasswd: ENC[AES256_GCM,data:o3aXzl6R+PuBem0Sd/aDr3S8VhTzyQpTkc9p++Jn8OFzEW90qxDM,iv:oLtsPVtc4fMv0Em9ntUsw2PKkXdxBp/WKMb5JMJjM+I=,tag:kI6of9v9o9yM74Go321FMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnL3l4OVhQaHkxY3hrbmpS
            dnRFSTJSVHkzMm45N01BY0duaUVxK0J0Q21BCmNqYStzQkhodzhzdTBSSTVHaHRy
            VjBqdEdZNm1FL1kxQnFBNGpWR29OZU0KLS0tIGhIMWFRaU1NSWozN0xwSy8rRDYy
            eXJZZ3RNZzVTLzdwMXZFSE9CZ1VseHcK/bsN4ZOKG732S/mQahYBKZI2Tv666u0F
            INPZLOxAstcCI14wUUh/F4LmPQHXf5M6G5QORTeXVz4ISPS09sHYWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIa0N5TmhpWHB3UzFvZy85
            TWVYMit1TWl6UmQ1NjRIdWlud1VINmk4WUFFCndNM2NJS0J0L29Wb2lZZmVWQllu
            QzRjSHh2bHZ2QVZvYU45K3BqU3hjdm8KLS0tIHhRVEVUTlpqbExjSFN2NC9BczhT
            eEFFam5YRzZTOWI1NkNON05jV3hVWFEKF2hVYrvTRRkemq/Tc4g4XZECjIxTxB39
            n99SVKbgMMEDlh/yCLQkZ+iZsbBY7v/ocQsCrAqpNZJ1tf25U7NJyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d70v7e0uyptut9mjuh06zsdt7udslentsp3ernvtwhemnlgz6s3s2587sr
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^credentialsJson|^secret_key$|.*[Pp]assword$)
    lastmodified: "2026-10-03T14:52:41Z"
    mac: ENC[AES256_GCM,data:XVXgmFPmRiFnkftf/4o9VPwCokrsTFiVKzEHFo9/cewezAlkJcZPeV887tWxk/6vNHJ3iOaP68KojuJYDskjsvcH6RK7g2JgjyKZ+K20Y+s8GHMQ1OELOqr++oaGwvpewKv5nKJzIhshhN+dM5DS4nSrJATQJec4JXP6zNTi+5E=,iv:+e55XeQpUl+syZbT+7fBDkbkhfOY3kdrsefyWZCO29M=,tag:qZWiBDS7z0wkm1g4diJ+NA==,type:str]
    version: 3.13.3
