# Read by vars/nut.yaml and group_vars/all.yaml: the upsd accounts on the NUT server.
admin_password: ENC[AES256_GCM,data:+NF1kHLf7A==,iv:OIkOYL4Zh/5eFOP5hgMtiwkHvNseueG477txHu189PQ=,tag:nqMiUEcEHoSHD2Wv+jlspw==,type:str]
localuser_password: ENC[AES256_GCM,data:yqsy3Ig3iQ==,iv:yXvlRbzHgGnxRDt4FW/2Xz+r4iMzX7qzvVGTKKBId7c=,tag:HdtFndddVgMCLdk+ehcQ+A==,type:str]
remoteuser_password: ENC[AES256_GCM,data:Mmy2DqkKhw==,iv:pN6ELtYD2y8Og04dAn0BjjBzqxNnq1R/aKAvTmYS/i8=,tag:OS5o3dKRaCzmpp+G2F7z1g==,type:str]
monuser_password: ENC[AES256_GCM,data:/LPC8k4l8Ng0NAq8wpDm8pUnhDh/XY9O8w==,iv:4Y27jNYD8LZFX7+CyNovgRJITe84sD+V/GB4prV98RE=,tag:dD9EdfDSvzTyPkpcVjyDZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpS0RLSU9MZlJ3UXhCQ3ho
            V2c0Zi9uVnphZnlETUNWb2pPMTJjeTN2RzJRClgrcW8vL0orVlErMnFOT2tsSVZu
            R1FmRmRDbmNMdGpvVW5sQ2dVeU9hdzQKLS0tIHZtR2NzTDRYRFdXZExsNTRLOERK
            L0JneVpYNTM1bC9KRHlzYUd1MzEvT0UK27akfdWR+jQCAz/460NxI0Vs/2/l4zi/
            mEIMSigMapnIPr2eYznu9Bt0Ij8buxUgYCezVC9p12/ADGwJc+ZwfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^credentialsJson|^secret_key$|.*[Pp]assword$)
    lastmodified: "2026-10-06T15:16:57Z"
    mac: ENC[AES256_GCM,data:dQ/CcCMDc2LmZpp277+U/w3QQ8FHsyvcUxPHRmx7WPsN8MwhDBWk+DFTfVBs4bsM2WMqRA2acep1uj3LLKF9WusPQxNiEZHtH17bWDQuyRW2l7c/VEw+Kp7/AmG1lirfaW0FnWu+M0KAUqQdCyQByq4QRLW+WVR7DFe5ntsU4Jc=,iv:0LHnznWUpENHbM7ECP+wKWoHZsbCk0wmqCoN7DUsIU8=,tag:VwUO2DpcMdNDoDhPnX0yzg==,type:str]
    version: 3.13.3
