# Read by vars/setup.yaml.
nut_password: ENC[AES256_GCM,data:3iau8E3z+Q==,iv:8gufyS6XH72TJKvhIz4Pb0cJyrvILnHaYWB1IfvU/cE=,tag:9MmP3Hjlxvwg0KbhkHFi7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSkxJUHZTeXBUdG0veDRx
            ZnRmUllPUjMrMXZTVVhHSDdubWNYWXNtcFE0CmxZMlBMQStoRzZFOG9iRjFXOG90
            QkljdDkyNEJUYkpzZjFYY3ZNZG1uekkKLS0tIEx3RzF0SXFibVQ4SG94Vjlsdk1J
            TDA0TWNreE1TSE1JblcxSHdvd1V2OFEKXdELfu/WnLKIOASc+wNGGoyg3JJvRi7q
            TCWIm8ZCyqZbvvXwqloVxv6HpJlw8L+FNtASjkjmcIWCux0i+mYbeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^credentialsJson|^secret_key$|.*[Pp]assword$)
    lastmodified: "2026-10-04T02:55:04Z"
    mac: ENC[AES256_GCM,data:cXBz6NSbJ57bbZDE6eZHrCaXvxS8Ca33GJv2FzjoSZ6a9SQSVRSyIFgTDkQjCwzHluZ6aN6+FlVAlDrdieVj/6wpUYBOrviKRriiq9cvDbs9ZtCIdasdSPg8ljXKnOrWkZBnGfoEJHfhak6lGTmSvmO10kpjtKakh+PFXhz4FEI=,iv:IJpVq7vbH3vKEWPjQBlnZsev6nlLNXJN9LNx0voa/DE=,tag:1NFqpVmPEw8oxz2fRopmKA==,type:str]
    version: 3.13.3
