---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: barrelmaker
spec:
  releaseName: jellyfin
  chart:
    spec:
      chart: jellyfin
      version: "0.7.1"
      sourceRef:
        kind: HelmRepository
        name: barrelmaker
        namespace: flux-system
      interval: 1h
  values:
    persistence:
      config:
        storageClassName: longhorn-protected
        size: 3Gi
      media:
        storageClassName: jellyfin-media
        size: 50Gi

    httpRoute:
      enabled: true
      parentRefs:
        - name: "poseidon"
          namespace: "envoy-gateway-system"
          sectionName: "https-wildcard"
      hostnames:
        - "jellyfin.barrelmaker.dev"

    resources:
      requests:
        cpu: 700m
        memory: 512Mi
      limits:
        memory: 1500Mi
