---
galaxy_info:
  author: Nolan Cooper
  description: Generate Talos machine configuration for the control plane nodes.
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions: [all]
    - name: Ubuntu
      versions: [all]
  galaxy_tags: [talos, kubernetes, bootstrap]

dependencies: []
