---
- name: Create User Namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ workload_namespace }}"

- name: Set Namespace in kubectl context
  changed_when: true
  ansible.builtin.command: >
    kubectl config set-context
    --current
    "--namespace={{ workload_namespace }}"

- name: Create User Resource Quota
  kubernetes.core.k8s:
    state: present
    template: resourcequota-user.yaml

- name: Create User Limit Range
  kubernetes.core.k8s:
    state: present
    template: limitrange-user.yaml

- name: Set workload role path
  ansible.builtin.set_fact:
    workloads_role_path: "{{ role_path }}"

- name: Create Jellyfin Media Persistent Volume
  kubernetes.core.k8s:
    template: "{{ item }}"
  with_fileglob:
    - templates/pv-jellyfin-media.yaml

- name: Setup Helm
  ansible.builtin.include_role:
    name: helm
    tasks_from: setup
  vars:
    helm_repos:
      barrelmaker: https://charts.barrelmaker.dev

- name: Deploy Helm Charts
  ansible.builtin.include_role:
    name: helm
    tasks_from: deploy
  loop: "{{ helm_charts | dict2items }}"
  vars:
    helm_chart_name: "{{ item.key }}"
    helm_chart_ref: "{{ item.value.ref }}"
    helm_chart_version: "{{ item.value.version | default('latest') }}"
    helm_chart_namespace: "{{ workload_namespace }}"
    helm_chart_values_template: "{{ workloads_role_path }}/templates/values/{{ item.key }}.yaml.j2"
    helm_chart_sops_file: "{{ workloads_role_path }}/files/{{ item.key }}.sops.yaml"
    # To pin a version, add it to the dictionary: { ref: repository/chart, version: 1.2.3 }
    helm_charts:
      ingress: { ref: barrelmaker/ingress }
      jellyfin: { ref: barrelmaker/jellyfin }
      niucraft: { ref: barrelmaker/minecraft }
      pistachio: { ref: barrelmaker/pistachio }
      satisfactory: { ref: barrelmaker/satisfactory }
      website: { ref: barrelmaker/website }
      factorio: { ref: barrelmaker/factorio }
      loch: { ref: barrelmaker/factorio }
      obscura: { ref: barrelmaker/obscura, version: 0.6.1 }
      devscura: { ref: barrelmaker/obscura, version: 0.7.0 }
      # serge: { ref: barrelmaker/serge }
      # gmod: { ref: barrelmaker/gmod }
      # valheim: { ref: barrelmaker/valheim }
