---
- name: Create User Namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ workload_namespace }}"

- name: Set Namespace in kubectl context
  changed_when: true
  ansible.builtin.command: >
    kubectl config set-context
    --current
    "--namespace={{ workload_namespace }}"

- name: Create User Resource Quota
  kubernetes.core.k8s:
    state: present
    template: resourcequota-user.yaml

- name: Create User Limit Range
  kubernetes.core.k8s:
    state: present
    template: limitrange-user.yaml

- name: Create Jellyfin Media Persistent Volume
  kubernetes.core.k8s:
    template: "{{ item }}"
  with_fileglob:
    - templates/pv-jellyfin-media.yaml

- name: Install Helm
  become: true
  community.general.snap:
    name: helm
    classic: true
    channel: latest/edge  # needed because helm 4 breaks things

- name: Check if Helm Diff is installed
  ansible.builtin.command: helm plugin list
  register: workloads_helm_plugins
  changed_when: false

- name: Install Helm Diff
  ansible.builtin.command: helm plugin install https://github.com/databus23/helm-diff
  when: "'diff' not in workloads_helm_plugins.stdout"
  changed_when: true

- name: Add Helm Repos
  ansible.builtin.command: >
    helm repo add {{ item.key }} {{ item.value }}
  loop: "{{ helm_repos | dict2items }}"
  vars:
    helm_repos:
      barrelmaker: https://charts.barrelmaker.dev
  changed_when: true

- name: Update Helm Repos
  ansible.builtin.command: helm repo update
  changed_when: true

- name: Deploy Helm Charts
  ansible.builtin.include_tasks: deploy_chart.yaml
  loop: "{{ helm_charts | dict2items }}"
  vars:
    chart_name: "{{ item.key }}"
    chart_ref: "{{ item.value.ref }}"
    chart_version: "{{ item.value.version | default('latest') }}"
    # To pin a version, add it to the dictionary: { ref: repository/chart, version: 1.2.3 }
    helm_charts:
      ingress: { ref: barrelmaker/ingress }
      jellyfin: { ref: barrelmaker/jellyfin }
      niucraft: { ref: barrelmaker/minecraft }
      pistachio: { ref: barrelmaker/pistachio }
      satisfactory: { ref: barrelmaker/satisfactory }
      website: { ref: barrelmaker/website }
      factorio: { ref: barrelmaker/factorio }
      loch: { ref: barrelmaker/factorio }
      obscura: { ref: barrelmaker/obscura }
      # serge: { ref: barrelmaker/serge }
      # gmod: { ref: barrelmaker/gmod }
      # valheim: { ref: barrelmaker/valheim }
