apiVersion: v1
kind: Secret
metadata:
    name: sops-age
type: Opaque
stringData:
    #ENC[AES256_GCM,data:DhQ8S+fCdm5MlSGiOmydVGCGAlOCunFl25YWHh396VHQU3irS8tL,iv:RB+tR0fwKnbvZ2avjh5Vv7gXpYlkxKrj71YrHfGXGJ8=,tag:1kdcUGkssnw5n7MU03rYSQ==,type:comment]
    age.agekey: ENC[AES256_GCM,data:ol/ozjy2soiwmtdW8l/MGzK5TfXpXlIyzGTxSGBkKJZDmNe/AUumrIiP1mAX6ViE7aupyL/182wVYg7u6y7W5xAZimK/LkPPbw2rGyjtfqjRrP3cNJE/BrAEVGy4AvpUP/x4gFUCIjq5/4HCAn3lV3ls2gEL4jBWJC9E1jtGQXm9LjFwO2unXWR3Q9ZT4Xs6Az2Rb6f7rc7p8JZcaFQmATZl4vByFWX1mRUWaRH7aMgf/Vhfo12OcHkj/Z6Z,iv:39GjTb4QsaL4FNcQsDzL+N+gYFGbHmhl3U6DgeBgMlU=,tag:EC0DdtDhUva+Y0jTvy2WEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWFk5QkkwZnV1OXo4QVhH
            cFV6a0VLemZpeWFCeGNHSXZIcnhKWEZ1S3lNCnhsN1Q0eUZCVm8yQm9lVk9ET1pn
            TXc5K2F4ZjNpTzY1WStTcnZnOGpXTzgKLS0tIEhlKzMwRlNZUVBOMFhGd1FWdmFF
            NFdTOVFHalBsNlpydzVIM1JMVjROd1kKc+KcW2x4Nzl0V5z5j+aE0VORiunMp1wx
            xuP/GbT6IxZmAosr3RAbQckP19wiGiNcgqalpK0+0XsQ8MZ23SrHZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^credentialsJson|^secret_key$|.*[Pp]assword$)
    lastmodified: "2026-09-30T23:53:01Z"
    mac: ENC[AES256_GCM,data:ybr1zJNKWpgLV0ve2QzpDx5spzwpDseK/WMpX1roGSzukoWs2SIgHTicz2zIHSk715VeLP7B7b5pLLsIISNuuH8pVZaexuDzHM+uc7VoXkluS15tq7BRszjDh23zWUwrR7uXKFB0ftRrw45F2xYtiaoClpodIvMk6zDkQeY1Sys=,iv:CtV9pnSzjQ/1+Zr8CqXximubSjbVx1ImtVKZFoLKFvM=,tag:2i7yJfrQnpZsxIsOguKIVw==,type:str]
    version: 3.13.3
