apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:lfuVmichx422iHYDHlNQgHypYpJ0dVNV+h2TZGdCPttsb0WuNs2HcH8gYSHO0scq+pzdlt0=,iv:nVmWw5clq1ijir0k3MhouCysjmF/cR1m1Q9krRi6F5Y=,tag:mM5CB6/JNjFKkJyROHv5Cw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOXRlK3B4Uk1BQVlMa05N
            RWxnU1l5d2d6VGVieTU5N3VSWHVWYUZraFhzCk14YzBWbkxTUi8yeHUyQjFxU3Vt
            UnB1UnVHTitRZytQYkdxNUN6K3VLZHcKLS0tIE1NUysrRUVNT3k0M1plZVdRdjRT
            aUZDL3ZDNDUxSmhkSkM2WTRob25hODQKNWaBRAUNtj2Tf6ZNTueLjvvnpV5y1/N2
            xTQANtfd5WxkZb0DMzyX/Utml1lGnl21TTyHthj4pSRW7pzGnZ3+jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbnZtbEw5NjJjQ3VYZVEz
            bmxZcHJEaW8vcWxibzJkVTl5MW1yMGtaU3lnCmt3RUhtTWxMck5VbGZ3RjQrV1ZM
            d2RDY3FmQmprMVFzaDZ4SWdqTHZKV1kKLS0tIGpMZnJVYWdiQjBqV295WVcwQkc2
            YXJWM3BUTEtkTnIrdFFVS3JZZ3BkMkUKyDclIXTyea8lE667XCHrul3eAz1IzvS5
            LThMCLe+AqicaKV23kDLYJS+YoJKx5x3qJzp+FJDasJSmhAqafuX1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d70v7e0uyptut9mjuh06zsdt7udslentsp3ernvtwhemnlgz6s3s2587sr
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^credentialsJson|^secret_key$|.*[Pp]assword$)
    lastmodified: "2026-10-03T00:20:07Z"
    mac: ENC[AES256_GCM,data:L8vgJ2oEyGciimKfRSxamCHnKf3fG6mYA7XguepVDy3rIAxJCnHdE2WTqi8/zJeUJuMcefuy5erCgAll8Mfb8W14qcSN+6oUdRYMKxHCUhvGR79hAqPIvggB8tu4N6IpglHuFPz14bNgYYuYrfXt/gFbeLWHYlPCBafbR9YOZpE=,iv:G/VnfbV6eecOGu0MCh1ndpUPBj6Qq9TJ9GOYfH7gIck=,tag:Su99gI6+BPJaZINgWr0FsA==,type:str]
    version: 3.13.3
