# vim: ft=yaml
---
apiVersion: v1
kind: Config
preferences: {}
current-context: {{ cluster_user }}
clusters:
- name: microk8s-cluster
  cluster:
    certificate-authority: {{ cluster_user_api_crt }}
    server: https://{{ cluster_host }}.{{ local_domain }}:{{ cluster_port }}
users:
- name: {{ cluster_user }}
  user:
    client-certificate: {{ cluster_user_crt }}
    client-key: {{ cluster_user_key }}
contexts:
- name: {{ cluster_user }}
  context:
    cluster: microk8s-cluster
    user: {{ cluster_user }}
    namespace: {{ cluster_user }}
