# vim: ft=yaml
---
apiVersion: v1
kind: Config
preferences: {}
current-context: {{ cluster_user }}-{{ cluster_host }}
clusters:
  - name: {{ cluster_host }}
    cluster:
      certificate-authority: {{ cluster_user_api_crt }}
      server: https://kube.{{ cluster_domain }}:{{ cluster_port }}
users:
  - name: {{ cluster_user }}
    user:
      client-certificate: {{ cluster_user_crt }}
      client-key: {{ cluster_user_key }}
contexts:
  - name: {{ cluster_user }}-{{ cluster_host }}
    context:
      cluster: {{ cluster_host }}
      user: {{ cluster_user }}
