apiVersion: v1
kind: Secret
metadata:
    name: discord-webhoook-url
    namespace: monitoring
stringData:
    url: ENC[AES256_GCM,data:yjWnt35Ytg7d8iVgVOkuU4yJOnzUjAi0IPDjug6Pw+DM1jixre4RgrooWJioVgp4sXU/a8b1OPD/cLyWp6JMnCuzjw99UUUV2ISmht0AWFehjNTbYG0xqAq0BY80j0u5r7kjeKgjj7Ez+wZoqQJeqviDoMhgpjQYqDrbWA==,iv:5V8P4z5F82jirdOxxjVXIeWM9mxFl24Zpi4aAlx1Va0=,tag:FZnqCdeW50oLYr6In/U96g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0S3BrTTYzMi9adkwxc3lo
            c1BDcDVTM1FsZHczekhycXNVZGpJbUxMVjFNCjhCOHdwbnR5RDRwanZNK0FsTVNt
            azJUNWFpdHIyTjhodW1kVXpTY3YxQWcKLS0tIEE3VlRGV0VnY1pNOHRLRU80cXNR
            dHoyaUJkTEU1RnpQSXlJZkFBbzlBTVEK5O0Q3ts3Q5ALkp7xnxhkpNRCNflcoPp4
            i6s5cqjksnSQiT4rKt88SmLQFQq/CiRzt/MD9asjkWpmWPnYWHFHYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSzFXbzY3SytyOGRkUGpN
            Zk1oTG1BemJyaTlySUhzODhveG1tV0dHWmlJCkppSU16U3VSR05RSjlVUkpRZi9E
            a3dMaGVwRllxNGt1TDNyeUNEdmxzK28KLS0tIE15UUpKUGV1RWZ2YjhhdFhMRVRZ
            ckkxSEY1S3JJNnFnRktqUTdmWFhFNzQKivXbFa11ZBOlplQQLw0N58SZ2Unbmtaa
            1u9+DLzM64j4CO4hv+nhHTvb6MoNI58ehMHXBErTe03bYcRq97wNZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d70v7e0uyptut9mjuh06zsdt7udslentsp3ernvtwhemnlgz6s3s2587sr
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^credentialsJson|^secret_key$|.*[Pp]assword$)
    lastmodified: "2026-10-03T14:36:53Z"
    mac: ENC[AES256_GCM,data:X1yTZTLfVewkjJ6uKy1L05xnpI1/s0BZfOvl6VJgxPSqik0oKfj6veFSr0VmHK96jVauJ4DSc3NtLBox0L4JjBP2fQv8qTpIqFuHylCoJev2/wun21HMgA5mvHXbSfGjaziH0NUtObTw4ySKTMATg0Mux2HYHYl6u9uXGlT7HCY=,iv:ZEp9kG6P6+snoBjmmV0a5wdVmuTTiHl2JWwGDtQaBVw=,tag:sMjKWmmZrIKq+xe1w2H/tw==,type:str]
    version: 3.13.3
