apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:bGoxiG51M/7dIis=,iv:kkdDXBCsbGwyo1N6zcMrabhyb3oEIE2qPTxy5Wh4RWQ=,tag:0salQGz9LXceMcye6dEKgQ==,type:str]
    admin-password: ENC[AES256_GCM,data:KuvgC6bWB9jR4niH2sxxmlo1hg==,iv:Lj9WRCSjV9OnEJa8I4lDSrv7YeAel6yIJK4B/5VJ4dU=,tag:E2O+MAdVmuEokSOpJyxbBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVFN4MGh1RTVJcjZ4RWpE
            WXlaSHJSR2QweENnZ3ZsZkZxRG1wVWxUSmxBCnE4V0srcHBka2k0VEwrSjBOdERn
            a1hDTk5jZHpubUxNQmx1OEtUdzBuM2cKLS0tIExzcTJFQ0hKcHVES3FlREE2aTcv
            SnlkTFNTQnBjREw5UGZHd2hNcDNMaWsK+Bu+4ZdbtCHGLNLp6mHqOki2h0nGfd/q
            ukq7yFfGygiQTnZ3GzHj4uLrYqgoRt58Sf0pNp7ph/8R+GY4ZPXLtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk5ucdcd2nzjs2ztpfhr2l0ds284p284f2c7grcmns7hsl0hp42syku7c6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMFBqdk0vNndTQnBWY3lS
            cnNPdmplWEJkejArMlFjeTdaNFVFTlhmNFdFCmF1WTJDSzR2eTd1STV0RVlQcElM
            eHhUWmlROENJbHFMT3EzNnFRc1BRVzAKLS0tIFFWNzRpeXlicmN4bStrMkRUZFFM
            YVhzZ2F0bDk0dG1LN29tNHlwUDlxMzgK5h+rRWqwuTf5tSFHwzlrNZLTDWEI+8DH
            wTsIiFleCcRgafGotwUIfZE+ISgr0T+YUsVv1YVYnuhGNj6sHvpORg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d70v7e0uyptut9mjuh06zsdt7udslentsp3ernvtwhemnlgz6s3s2587sr
    encrypted_regex: (^data|^stringData|^cluster|^secrets|^jwtSecret|^certs|^trustdinfo|^credentialsJson|^secret_key$|.*[Pp]assword$)
    lastmodified: "2026-10-03T14:36:53Z"
    mac: ENC[AES256_GCM,data:S3a9It2DLLQCcEET2KbVk9MPDR/K1GfmZhjkAaL+Jan6J/LSCGkg0zE92NDBwxgVSJgKcrkHaXSve3WE0bPQNiYN112NJXPd7UfXAfIZTHHazWnsnt34QOE8zXEJz/8aFz1ybEKrgKnwQ8U61fFJSxtTNyAB2wRdpFqc5LluZug=,iv:YS/kwbowpXa66W2NboKsh153FlsfF6PGNMEN39ELAQ4=,tag:+VSXLIcxzR5ebZWFSjoIyw==,type:str]
    version: 3.13.3
