cluster:
  allowSchedulingOnControlPlanes: true
  controllerManager:
    extraArgs:
      bind-address: 0.0.0.0
  proxy:
    extraArgs:
      metrics-bind-address: 0.0.0.0:10249
  scheduler:
    extraArgs:
      bind-address: 0.0.0.0

machine:
  certSANs:
    - {{ node_hostname }}.{{ local_domain }}
  install:
    image: factory.talos.dev/installer/{{ factory_response.json.id }}:v{{ talos_version }}
    disk: {{ install_disk }}
    wipe: false
  network:
    hostname: {{ node_hostname }}
    interfaces:
      - interface: {{ interface_name }}
        dhcp: true
        vip:
          ip: {{ cluster_vip }}
  time:
      disabled: false
      bootTimeout: 2m0s
      servers:
          - {{ ntp_server }}
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
