{
 "title": "Minecraft",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "service",
    "label": "Server Name",
    "query": {
     "query": "label_values(mc_players_total, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Online Players",
   "type": "stat",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(mc_player_online{service=~\"$service\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mc_jvm_memory{type='max', service=~\"$service\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "mc_jvm_memory{type='allocated', service=~\"$service\"} - scalar(mc_jvm_memory{type='free', service=~\"$service\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Tickrate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mc_tps{service=~\"$service\"}",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Players",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mc_players_total{service=~\"$service\"}",
     "legendFormat": "Unique"
    },
    {
     "expr": "sum(mc_players_online_total{service=~\"$service\"}) by (world)",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Loaded Chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mc_loaded_chunks_total{service=~\"$service\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Villagers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (mc_villagers_total{service=~\"$service\"}) by (world, level, profession)",
     "legendFormat": "{{world}}:  {{profession}}  (lv{{level}})"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (mc_entities_total{service=~\"$service\"}) by (world)",
     "legendFormat": "{{world}}_total"
    }
   ]
  }
 ]
}