---
persistence:
  storageClassName: factorio
  size: 2Gi

serverPort: 30002  # Must be in the range 30000-32767

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 845
  runAsGroup: 845
  fsGroup: 845

securityContext:
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 800m
    memory: 1000Mi
  limits:
    memory: 2000Mi

metrics:
  enabled: false
