---
persistence:
  storageClassName: longhorn-local
  size: 5Gi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 845
  runAsGroup: 845
  fsGroup: 845

securityContext:
  capabilities:
    drop:
      - ALL

service:
  type: LoadBalancer
  port: 34197

resources:
  requests:
    cpu: 800m
    memory: 1000Mi
  limits:
    memory: 2000Mi

metrics:
  enabled: false
