---
persistence:
  storageClassName: niucraft
  size: 30Gi

dynmap: true
metrics: true

properties:
  aikarFlags: true
  enforceWhitelist: true
  memory: "6G"
  motd: "NIUCraft Server"
  ops: "Barrelmaker97"
  existingWhitelist: "SYNCHRONIZE"
  existingOps: "SYNCHRONIZE"
  paperChannel: "default"
  serverName: "NIUCraft"
  spigetResources: "36618,69584"
  modrinthProjects: >-
    dynmap:beta,
    chunky
  type: "PAPER"
  version: "1.21.1"
  viewDistance: "32"
  whitelist: >-
    BakerGang2022,
    Barrelmaker97,
    Lil_Doza,
    LuckierDodge,
    Solo22499,
    Spronix,
    ThePrimeus,
    ninjahomie7

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

service:
  type: LoadBalancer
  port: 25565

resources:
  requests:
    cpu: 1000m
    memory: 7000Mi
  limits:
    memory: 8000Mi
