---
serverName: Valheim
serverPort: 30005  # Must be in the range 30000-32767
worldName: Asgard
public: true
metrics: true

persistence:
  storageClassName: valheim
  size: 10Gi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 111
  runAsGroup: 1000
  fsGroup: 1000

resources:
  requests:
    memory: 3Gi
    cpu: 700m
  limits:
    memory: 4Gi
