---
apiVersion: v1
kind: Endpoints
metadata:
  name: grafana-external
  namespace: "{{ cluster_user }}"
subsets:
  - addresses:
      - ip: 192.168.15.20
    ports:
      - name: http
        port: 3000
        protocol: TCP
