---
- name: Install age
  become: true
  ansible.builtin.apt:
    name: age
    state: present

- name: Install sops
  ansible.builtin.include_role:
    name: community.sops.install
  vars:
    sops_install_on_localhost: true

- name: Create Talos config directory
  ansible.builtin.file:
    path: "{{ talos_config_dir }}"
    state: directory
    mode: '0700'

- name: Get Talos Image ID
  ansible.builtin.uri:
    url: https://factory.talos.dev/schematics
    method: POST
    src: customization.yaml
    status_code: 201
  register: setup_factory_response

- name: Create control node machine configs
  loop: "{{ node_names }}"
  ansible.builtin.include_tasks: gen-config.yaml

- name: Clean up machine config patch
  ansible.builtin.file:
    path: "{{ talos_config_dir }}/patch.yaml"
    state: absent

- name: Generate Talos config
  changed_when: true
  ansible.builtin.command: >
    sops exec-file "{{ role_path }}/files/secrets.sops.yaml"
    'talosctl gen config --force
    --with-secrets {}
    --output-types=talosconfig
    --output "{{ talos_config_dir }}/talosconfig"
    "{{ cluster_host }}" "https://kube.{{ cluster_domain }}:{{ cluster_port }}"'

- name: Save Talos config
  changed_when: true
  ansible.builtin.command: >
    talosctl config merge "{{ talos_config_dir }}/talosconfig"

- name: Clean up generated talosconfig
  ansible.builtin.file:
    path: "{{ talos_config_dir }}/talosconfig"
    state: absent

- name: Add nodes to Talos config
  changed_when: true
  ansible.builtin.command:
    argv: "{{ complete_command }}"
  vars:
    complete_command: "{{ prefix + (node_names | product(['.' + local_domain]) | map('join')) }}"
    prefix:
      - talosctl
      - config
      - node

- name: Add endpoints to Talos config
  changed_when: true
  ansible.builtin.command:
    argv: "{{ complete_command }}"
  vars:
    complete_command: "{{ prefix + (node_names | product(['.' + local_domain]) | map('join')) }}"
    prefix:
      - talosctl
      - config
      - endpoint

- name: Print ISO download link
  ansible.builtin.debug:
    msg: "https://factory.talos.dev/image/{{ setup_factory_response.json.id }}/v{{ talos_version }}/metal-amd64.iso"
