---
- name: Create Cluster
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'cluster.yaml.j2') | from_yaml }}"

- name: Create Pod Monitor
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'podmonitor.yaml.j2') | from_yaml }}"

- name: Create Alert Rules
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'prometheusrule.yaml.j2') | from_yaml }}"

- name: Wait for Cluster
  kubernetes.core.k8s_info:
    api_version: postgresql.cnpg.io/v1
    kind: Cluster
    name: "{{ cloudnative_pg_cluster_name }}"
    namespace: "{{ cloudnative_pg_cluster.namespace }}"
    wait: true
    wait_condition:
      type: Ready
      status: "True"
    wait_sleep: 10
    wait_timeout: 900
