---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: "{{ workload_namespace }}-default"
  namespace: "{{ workload_namespace }}"
spec:
  hard:
    requests.cpu: 10
    requests.memory: 30Gi
#   limits.cpu: 20
#   limits.memory: 40Gi
