---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: "{{ workload_namespace }}-default"
  namespace: "{{ workload_namespace }}"
spec:
  hard:
    requests.cpu: 5
    requests.memory: 16Gi
#   limits.cpu: 10
#   limits.memory: 20Gi
