---
apiVersion: v1
kind: ConfigMap
metadata:
  name: observability-custom-headers
  namespace: observability
data:
  Content-Security-Policy: "frame-ancestors 'self'; default-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://grafana.com data:; img-src 'self' https://grafana.com data:; style-src 'self' 'unsafe-inline'; base-uri 'self'; form-action 'self';"
