---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: observability
  namespace: observability
  annotations:
    nginx.ingress.kubernetes.io/custom-headers: observability/observability-custom-headers
spec:
  ingressClassName: nginx
  rules:
    - host: grafana.{{ inventory_hostname }}.{{ local_domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: kube-prom-stack-grafana
                port:
                  number: 80
    - host: prometheus.{{ inventory_hostname }}.{{ local_domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: kube-prom-stack-kube-prome-prometheus
                port:
                  number: 9090
    - host: alertmanager.{{ inventory_hostname }}.{{ local_domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: kube-prom-stack-kube-prome-alertmanager
                port:
                  number: 9093
