---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/custom-headers: monitoring/monitoring-custom-headers
spec:
  ingressClassName: nginx
  rules:
    - host: grafana.{{ inventory_hostname }}.{{ local_domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: kube-prometheus-stack-grafana
                port:
                  number: 80
    - host: prometheus.{{ inventory_hostname }}.{{ local_domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: kube-prometheus-stack-prometheus
                port:
                  number: 9090
    - host: alertmanager.{{ inventory_hostname }}.{{ local_domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: kube-prometheus-stack-alertmanager
                port:
                  number: 9093
