---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: niucraft
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: niucraft
  local:
    path: "{{ local_storage_dir }}/minecraft/niucraft-data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "{{ inventory_hostname }}"
